### ISSUE TITLE
How to set a 4-week rolling period

### ISSUE THREAD

**Issue by martinval** [richardtallent/vue-simple-calendar#100]
Hi,
thanks for this great calendar. I'm trying to adapt the calendar view to always show a forward view of the next 4 weeks.  How can this best be achieved ?

In the current demo, when I select weeks as the unit of measure and 4 as the period, I get the 4 weeks, but the start is always at the beginning of the month and not at the beginning of the current week.

You can easily see this issue in the demo if you select a 1 week view. The view shows the first week of the month, even though we're already in the second, so you don't actually see today.

**Comment by naulacambra** [comment]
I've set up this [sandbox](https://codepen.io/naulacambra/pen/MPbQqY?editors=1111).

``` html
<div id="app">
	<h1>My Calendar</h1>
	<calendar-view
		:show-date="showDate" display-period-uom="week" :display-period-count="4"
		class="theme-default holiday-us-traditional holiday-us-official">
		<calendar-view-header
			slot="header"
			slot-scope="t"
			:header-props="t.headerProps"
			@input="setShowDate" />
	</calendar-view>
</div>
```

``` javascript
{
	el: '#app',
	data: function() {
		return { showDate: new Date('10/15/2018') }
	},
        component: {
              "calendar-view": window.CalendarView,  
        },
	methods: {
		setShowDate(d) {
			this.showDate = d;
		},
	}
}
```

And it displays correctly, the first week of the `showDate` and the next 4 weeks. How are you trying to achieve it?

**Comment by martinval** [comment]
Thanks @naulacambra , it was as easy as setting the showDate prop to today. The demo has this set to: showDate: this.thisMonth(1).
I was looking for a way to change the periodStart method inside the CalenderView component, but no need for that :)

**Comment by richardtallent** [comment]
Thanks naulacambra!
