### ISSUE TITLE
Dynamically added events randomly jumping

### ISSUE THREAD

**Issue by ux-powered** [richardtallent/vue-simple-calendar#104]
### Expected Behavior
Events must stay in the initial place.

### Current Behavior
Dynamically added events randomly jumps when moving cursor pointer over events in the calendar.

### Steps to Reproduce

1. Visit https://www.tallent.us/vue-simple-calendar/.
2. Add several events on the same date.
3. Move mouse pointer over any events in the calendar.

### Context (Environment)
Tested on:
1. Mac OS X 10.14 (Mojave)
    - Chrome 69
    - Safari 12
    - Firefox 63
2. Windows 10
    - Edge
    - Chrome 69
    - Firefox 59

### Detailed Description
When several events dynamically added on the same date, they are jumping randomly when cursor moves over any events in the calendar. It seems like the issue is not appearing on multi-date events.

The illustration:

<img width="223" alt="screenshot 2018-10-09 at 19 13 52" src="https://user-images.githubusercontent.com/39078782/46659871-200fc600-cbf9-11e8-815d-ffdd0d31e626.png">

↓

<img width="223" alt="screenshot 2018-10-09 at 19 13 42" src="https://user-images.githubusercontent.com/39078782/46659873-20a85c80-cbf9-11e8-8b08-e55597577722.png">

↓

<img width="223" alt="screenshot 2018-10-09 at 19 13 27" src="https://user-images.githubusercontent.com/39078782/46659874-20a85c80-cbf9-11e8-85a6-3c06afd69af9.png">

**Comment by richardtallent** [comment]
The component is working as expected, but this is a bug in the demo. It's because the demo does not assign unique `id` values to each new event added. Since the `id` property is used as the key for Vue rendering, the updates become unstable. I'll keep this open and fix in the demo when I have a chance.

**Comment by ux-powered** [comment]
Ok, thanks for the explanation.

**Comment by richardtallent** [comment]
Resolved in 4.2.0, just published. `id` is now *required* for all incoming calendar events.
