### ISSUE TITLE
Click-event fails to execute without event's id

### ISSUE THREAD

**Issue by vuphuctho** [richardtallent/vue-simple-calendar#108]
In [document](https://github.com/richardtallent/vue-simple-calendar#calendar-event-properties) for **Calendar Event Properties**, it states:

>` id` - A unique identifier for the event. Defaults to a randomly-generated string.

To my understanding, id for events will be automatically generated and added by the component.

However, if events provided to calendar does not have ids of their own, then `click-event` will not execute. 

Here is my [demo](https://codepen.io/vuphuctho/pen/ePjWMj) in CodePen, where one event has id and other doesn't. Click-event only works with the first one.

**Comment by richardtallent** [comment]
Update -- this will be added in 4.2.0, coming very soon... just need to do a little testing in Edge for another issue before I publish it.

**Comment by richardtallent** [comment]
Resolved in 4.2.0, just published. `id` is now *required* for all incoming calendar events.
