### ISSUE TITLE
Avoid using non-primitive value as key, use string/number value instead.

### ISSUE THREAD

**Issue by sean-atomized** [richardtallent/vue-simple-calendar#11]
Get the above Vue warning when running calendar (got it before updates as well).

I think the solution is to change line:

`<div v-for="day in daysOfWeek(weekStart)" class="day" :key="day" :class="[`

to

`<div v-for="(day, dayIndex) in daysOfWeek(weekStart)" class="day" :key="dayIndex" :class="[`

Seem to be having no issues with making this change (I did locally).

Thanks.

**Comment by richardtallent** [comment]
Ah! That must be a new warning, I just upgraded Vue in the package.json before I posted the new version and didn't think to look for any new console messages! Will patch it later tonight.
