### ISSUE TITLE
change language of items (month, week, years) header calendar

### ISSUE THREAD

**Issue by clamarque** [richardtallent/vue-simple-calendar#110]
Hello ! It's possible to change the language from item of select in header of calendar ? I can't find a solution for resolve this :/ . Thanks to help !

**Comment by richardtallent** [comment]
Are you asking whether you can add a language drop-down menu in the header?

If so, you would need to create your own custom header component (you can use the default header component as a guide), add your `<select>` field with the options you want (with the `value` attribute of each option set to the BCP 47 language identifier), and bind the value of that control to the `locale` prop of the calendar component.

**Comment by clamarque** [comment]
@richardtallent  Thanks ! I got it ! I don't was understands but your explain resolved this !
