### ISSUE TITLE
Not issue but question

### ISSUE THREAD

**Issue by anouanou** [richardtallent/vue-simple-calendar#111]
Hello,

I'm sorry to post this here but I've been trying unsuccessfully to add an event on the calendar for hours but still can't manage how to do it.

I want to add those events dynamically, I mean by this, not to write them directly in my code but with javascript for example.

My problem here is that I can't manage to know how to do to access to the data storing the variable.

If someone could give me an example with the sample code I would appreciate or some indications.

Thank you.

**Comment by richardtallent** [comment]
The demo application shows how to do this. Look here, on line 283:

https://github.com/richardtallent/vue-simple-calendar-sample/blob/master/src/App.vue
