### ISSUE TITLE
Clicking in CalendarViewHeader control navigates CalendarView and appears to refresh page

### ISSUE THREAD

**Issue by ausitpro** [richardtallent/vue-simple-calendar#117]
Hi - Cool component - thanks for your work on this!  

As stated in the title, when I click on any of the input areas of the period navigation controls in the header, the calendar updates as expected but then the page refreshes. There are two issues with this.  The first is that the calendar is implemented in a modal.  The refresh closes the modal and all hell breaks loose!  The second issue is similar in that the modal is opened from within a tab in a set of tabs, meaning that the current tab position is lost and the page resets to the initial tab. 

The long and the short of it is that the refresh really hurts! Is it expected/designed behavior that the click creates a refresh?  

Here is some code:

<template>
    <b-modal
    size="xl"
    id="modalAssetCalendar"
    ok-title="Ok"
    :title="title"
    :header-bg-variant="headerBgVariant"
    :header-text-variant="headerTextVariant"
    :body-bg-variant="bodyBgVariant"
    :body-text-variant="bodyTextVariant"
    :footer-bg-variant="footerBgVariant"
    :footer-text-variant="footerTextVariant">
    <b-container style="height: 750px">
      <b-form>
        <b-row>
          <b-col cols="12" style="display: flex; flex-direction: column; flex-grow: 1">
             <CalendarView
                :display-period-uom='periodUOM'
                :display-period-count='periodCount'
                :show-date="showDate"
                :events="events"
                @show-date-change="setShowDate"
                class = "theme-default"
                style="height: 750px">
                <calendar-view-header
                    slot="header"
                    slot-scope="{ headerProps }"
					:header-props="headerProps"
                    @input="setShowDate" />
             </CalendarView>
          </b-col>
        </b-row>
      </b-form>
    </b-container>
    </b-modal>
</template>
<script>
import {CalendarView, CalendarViewHeader} from "vue-simple-calendar"

export default {
    props:{
        bookings: Array,
        title: String
    },

    data: function() {
        return {
            showDate: new Date(),
            periodUOM: 'week',
            periodCount: 1,
            headerBgVariant: "light",
            headerTextVariant: "dark",
            bodyBgVariant: "light",
            bodyTextVariant: "dark",
            footerBgVariant: "dark",
            footerTextVariant: "light", 

            events: []            
        }
    },

    components: {
        CalendarView,
        CalendarViewHeader
    },
    
    methods: {
        setShowDate(d) {
            this.showDate = d
        }
    },
    
    watch: {
        bookings: function() {
            this.events = this.bookings        
        }
    }
}

</script>

**Comment by richardtallent** [comment]
Ah! I think I know what the issue it... the default header isn't using the "prevent" modifier on its buttons. I don't have time to fix it tonight, but will get to it ASAP as a minor bug fix.

**Comment by ausitpro** [comment]
Thanks Richard - I'll take a look also.

**Comment by ausitpro** [comment]
okay so not as simple as I thought.  I figured I could just change code in node_modules/vue-simple-calendar, do a build and everything would work out great... not so much?  This is a completely new environment for me so I'll have to understand things a bit better first.

**Comment by richardtallent** [comment]
All fixed now, just update to 4.2.1! Yeah, it's a good idea to treat the node_modules folder as basically read-only. It's just a local cache of your project's dependencies.

**Comment by ausitpro** [comment]
Thanks for the quick fix!  I've tested in my implementation and it works as expected now.
