### ISSUE TITLE
day num in cv-day-number should be configurable with month or not

### ISSUE THREAD

**Issue by shanbeileng** [richardtallent/vue-simple-calendar#118]

**Comment by richardtallent** [comment]
Sorry, I don't understand the issue.

I could maybe see having the name (or a short version of it on the 1st of the month's day number, especially on calendars showing multiple months. But I can't see how having the month on the day number in general would be useful. Can you elaborate?

**Comment by richardtallent** [comment]
Closing this for now, please feel free to re-open if you can provide more detail.
