### ISSUE TITLE
Event title wrap without hover event

### ISSUE THREAD

**Issue by jasonkpearson** [richardtallent/vue-simple-calendar#119]
apologies if this is a bit of a novice post ... but I've configured my calendar with larger event heights than default that should be able to accommodate most title use cases for me when the event title wraps (i.e. using wrap-event-title-on-hover renders the title beautifully).  I'd like the title to wrap by default instead of requiring a hover event.  I assume there would be a simple way to achieve this but nothing I've tried has worked. Any help would be appreciated!

**Comment by richardtallent** [comment]
You would need to:

- Override your CSS to set `.cv-event { white-space: normal }`. This allows the event titles to wrap.

- Set the `eventContentHeight` prop to a different height (the default is 1.4em, which takes into account the one-line height and the 0.2em of padding on the top and bottom). For example, if you want two-line events, you'd use 2.4em (or more if you want line-spacing of more than 1). This determines where the *next* event will be positioned on the same day.

- Set a `.cv-event { max-height }` value matching the  `eventContentHeight` plus the border width (2px by default, 1px top plus 1px bottom). This prevents any events from spilling over the allowed height.

Note that every event has to have the same height. It can be one line, two, etc., but arbitrary heights won't work correctly.

Granted, if you don't set the `max-height` as described above, the events will have an arbitrary height, but if there's more than one event on any given day, they won't "stack" correctly. Still, if you only have one event max each day, you could get away with that.
