### ISSUE TITLE
Date throws proper date placement off

### ISSUE THREAD

**Issue by sean-atomized** [richardtallent/vue-simple-calendar#12]
I changed one of the items to 2017-03-14 (March 14th, 2017) and ended on 2017-03-17 (March 17th, 2017).  This particular item did not render into the correct day.  Not sure if same thing happens else where.

**Comment by richardtallent** [comment]
Hi Sean, can you give an example of your event data? I played around with those dates and didn't notice any issues.

Note that the `startDate` and `endDate` attributes on the events need to be `Date()` values, not strings--the code doesn't currently attempt to parse strings, so if you're literally changing the event to something like `startDate: '2017-03-14'`, it won't be able to render the event, but `startDate: new Date(2017,2,14)` should work.

**Comment by richardtallent** [comment]
Hi @sean-atomized, did you get a chance to figure out some sample code to reproduce the issue?

I'm wondering if we're seeing a time zone issue here...

**Comment by houseoftech** [comment]
@richardtallent Could be related to time zone. I'm noticing an issue in your live demo. Drag any event to the first week of November / last week of October and it shows the start of event at October 29th.

![GIF of bug](https://thumbs.gfycat.com/OffbeatGrandioseAndeancondor-size_restricted.gif)

**Comment by richardtallent** [comment]
Fix applied, closing...
