### ISSUE TITLE
methods in live demo

### ISSUE THREAD

**Issue by Jochii12** [richardtallent/vue-simple-calendar#121]
Hello sir where i can find this function in your app.vue

this.dayDiff(event.startDate, date);
this.addDays(event.startDate, eLength)

is there a way to change a display in day instead of 10:23 AM Testing , i will 10: 23 "some string i want"

thank you.

**Comment by richardtallent** [comment]
Those functions are part of the `CalendarMathMixin` file, which is separate from the component but is imported as a mix-in. If you're unfamiliar with Vue mix-ins, here's some info:

https://vuejs.org/v2/guide/mixins.html

I'm sorry, I don't understand the other question. I think you may be looking for the `timeFormatOptions` property.
