### ISSUE TITLE
switch to spaces from tabs

### ISSUE THREAD

**Issue by houd1ni** [richardtallent/vue-simple-calendar#123]
Hello!

Thanks for the best calendar component that I could find 👍 

How about switching to much more common two spaces `  ` instead of tab, that renders differently depending on everything? It's the only real problem that I found during reading the code before integration ;) especially directly on github.

**Comment by richardtallent** [comment]
Thanks!

I'm solidly in the "tabs for life" camp, and that is the hill I will die on. :)

To view any code blob in Github with two spaces for each tab, just add `?ts=2` to the URL. You can even make this a bookmarklet if this is something you need to do often. I completely agree that 8 spaces per tab is a ridiculous default, and I wish they would make it a user setting.

And of course all code editors have some sort of tab size setting, so you can adjust the margins to whatever works best for you there as well.

One of the many benefits of tabs is actually that each programmer can have their own indentation settings without them being baked into the code. I prefer a 4-space indentation myself.

**Comment by houd1ni** [comment]
Gosh! Thanx! `?ts=2` is magic! Definitely should be an option in account settings here.
