### ISSUE TITLE
How to use dayContent slot?

### ISSUE THREAD

**Issue by jusvu** [richardtallent/vue-simple-calendar#125]
Hi! I'm using the latest 4.2.1 calendar and trying to add a text (number of events each day) in the calendar and I assume it can be done using dayContent. But I cannot figure out how to do it... I think I need to define slot="dayContent" somehow, but how? Please help =)

**Comment by szydloit** [comment]
Try
` <div slot="dayContent" slot-scope="{ day }">{{getSth(day)}}</div>`
