### ISSUE TITLE
Drag events dont work fine

### ISSUE THREAD

**Issue by Franklonchas** [richardtallent/vue-simple-calendar#127]
Hello,

I have noticed that when you drag events from one day to the next, they do not put themselves at the first good, but instead put them on the next day from the side that has been dragged. It's the second time when he does it right.

This I understand is not correct behavior. Is there any way to fix it?

Thanks and best regards!

**Comment by richardtallent** [comment]
Hello,

I'm not seeing any unexpected behavior. Can you please try this demo and provide a screen capture of the issue you're seeing?

https://www.tallent.us/vue-simple-calendar/
