### ISSUE TITLE
Depending on viewport, borders dont show up

### ISSUE THREAD

**Issue by kevinhofmaenner** [richardtallent/vue-simple-calendar#13]
![image](https://user-images.githubusercontent.com/10161858/31561973-b78472a4-b027-11e7-8f54-8e7f5f812b03.png)

> Chrome 61 on Mac OS X (Yosemite) Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

Depending on the viewport, the left border will not show up. This is an artifact of using percentages. I was able to fix this buy calculating the percentages rather than having them hard coded.

.calendar-month .event.offset0 { left: calc(.05em); }
.calendar-month .event.offset1 { left: calc(calc(100% / 7) + .05em); }
.calendar-month .event.offset2 { left: calc(calc(100% / 7) * 2 + .05em); }
.calendar-month .event.offset3 { left: calc(calc(100% / 7) * 3 + .05em); }
.calendar-month .event.offset4 { left: calc(calc(100% / 7) * 4 + .05em); }
.calendar-month .event.offset5 { left: calc(calc(100% / 7) * 5 + .05em); }
.calendar-month .event.offset6 { left: calc(calc(100% / 7) * 6 + .05em); }
.calendar-month .event.span1 { width: calc(calc(100% / 7) - .05em); }
.calendar-month .event.span2 { width: calc(calc(100% / 7) * 2 - .05em); }
.calendar-month .event.span3 { width: calc(calc(100% / 7) * 3 - .05em); text-align: center;}
.calendar-month .event.span4 { width: calc(calc(100% / 7) * 4 - .05em); text-align: center;}
.calendar-month .event.span5 { width: calc(calc(100% / 7) * 5 - .05em); text-align: center;}
.calendar-month .event.span6 { width: calc(calc(100% / 7) * 6 - .05em); text-align: center;}
.calendar-month .event.span7 { width: calc(calc(100% / 7) * 7 - .05em); text-align: center;}

**Comment by richardtallent** [comment]
Hi Kevin, did you have a chance to see my follow-up note on your PR? I can reproduce the border issue, but not the fix.

**Comment by richardtallent** [comment]
Fixed by https://github.com/richardtallent/vue-simple-calendar/commit/6f821fd8766d9844f4719acfac39d5cd8be191b4
