### ISSUE TITLE
vue-cli-service: command not found

### ISSUE THREAD

**Issue by antonioandrade** [richardtallent/vue-simple-calendar#130]
Hey @richardtallent 

One of my projects was requiring `master` and (since this week's commits) I started getting this:

![image](https://user-images.githubusercontent.com/1588621/59919101-7981f300-941e-11e9-9130-412fa205d15f.png)

during `npm install`.  

Any ideas? Is this a new build dependency?

**Comment by richardtallent** [comment]
Hi @antonioandrade,

`vue-cli-service` has been required for building for awhile, but until I accepted that PR, it wasn't part of the npm installation process. However, it isn't strictly required and the person making the PR didn't provide a use case for the change, so I may back that postinstall script back out.

As an FYI, for this project, I tend to work directly in the master branch while making changes and I may commit between successful builds, so it's probably not a good idea to refer to it directly in your code. Instead, pull the latest version posted on npm.
