### ISSUE TITLE
Issue installing on nuxt install.

### ISSUE THREAD

**Issue by AlbatiQue** [richardtallent/vue-simple-calendar#132]
Hey,

When adding the module to nuxt.config.js I get the following error.
<img width="1680" alt="Schermafbeelding 2019-06-26 om 16 32 24" src="https://user-images.githubusercontent.com/3764232/60188910-5ac19900-9830-11e9-81a0-c5b7aea68c38.png">

Thanks!

**Comment by richardtallent** [comment]
Hi! Unfortunately, I've never used Nuxt. I'm not aware of anything in the component that would be incompatible with SSR (there's no direct DOM or window references), but I wouldn't know where to start to look into this issue.

**Comment by chocochrispi** [comment]
@AlbatiQue Did you manage to solve the issue?

**Comment by AlbatiQue** [comment]
@chocochrispi yes I was able to make it work. 

create a new plugin file and call it calendar.client.js
`import Vue from "vue"
import * as CalendarView from "vue-simple-calendar"

Vue.use(CalendarView, { name: "calendar-view" })`

and import it in your nuxt config

**Comment by chocochrispi** [comment]
Great! thank you

**Comment by menepet** [comment]
I created a plugin file (plugins/calendar.js) and imported to nuxt.config.js plugins.

`import Vue from 'vue'
import { CalendarView, CalendarViewHeader } from 'vue-simple-calendar'

Vue.component('CalendarView', CalendarView)
Vue.component('CalendarViewHeader', CalendarViewHeader)
`

so i could use these two components immediately to my vue files as html components!

**Comment by richardtallent** [comment]
@menepet, I'm slowly working on the next version, which is based on Vue 3, uses Vite for builds, and is all TypeScript. I've run into some blocking issues with Vite around CSS and TypeScript, but I'm trying to get it worked out.

While I'd like to say this component supports SSR, I don't use Nuxt or have the time to learn it just to test compatibility. If you have any experience in using Vue3/Vite/TS with Nuxt, PRs to improve or test compatibility (without breaking the non-SSR use case) will certainly be appreciated as I try to get this new version out.

**Comment by phil-w** [comment]
I'm porting from Vue2 to Vue 3 and I'm getting the issue with `Cannot read property 'languageCode' of undefined`, which is trying to read from the none-existent "CalendarMath" thing, which I note "migrated from a mixin to a class" in the change log here. Hmm, Looks like I need to explicitly include that, or dummy something up to keep it happy. Any ideas anyonw?

**Comment by richardtallent** [comment]
This doesn't appear to be Nuxt-related...

You shouldn't have to import `CalendarMath` to use `CalendarView` or `CalendarViewHeader` -- they do their own imports internally. It's available for import in case you want to use some of those functions in your own header or event slow implementation.

I just pulled the repo and ran it locally and it seems to be fine (running -- in the IDE I did get a similar error). However, I'm a bit surprised it's working at all, since I thought imports in script tags weren't available for use in templates (you have to return them from `setup()`).

Either way, I've added the setup function so things are wired correctly and pushed a patch. I'll push it to npm later.

**Comment by mydnic** [comment]
> Hi guys! I'm getting this error over and over:
> 
> `Cannot read property 'languageCode' of undefined`
> 
> I'm already using the @menepet plugin declaration and still. I also tried with client side only plugin declaration.
> 
> EDIT: Solved This issue happens only with version 6, I downgraded to 5.0.1 and everything worked fine, just in case anyone gets here. I don't know if it's supposed to break with v6 @richardtallent

I have the same issue when upgrading from v5 to v6

My nuxt plugin looks like this : 
```js
import Vue from 'vue'
import { CalendarView, CalendarViewHeader } from 'vue-simple-calendar'

Vue.component('CalendarView', CalendarView)
Vue.component('CalendarViewHeader', CalendarViewHeader)
```

In my components :

```html
<calendar-view
            :show-date="showDate"
            :starting-day-of-week="1"
            display-period-uom="month"
            :items="events"
            @click-date="dateClick"
            @click-item="onClickEvent"
        >
            <calendar-view-header
                slot="header"
                slot-scope="t"
                :header-props="t.headerProps"
                @input="setShowDate"
            />
        </calendar-view>
```

Console error : 
client.js?06a0:103 TypeError: Cannot read properties of undefined (reading 'languageCode')
    at Proxy._sfc_render$1 (vue-simple-calendar.es.js?a834:545:1)
    at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:3569:1)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4070:1)
    at Watcher.get (vue.runtime.esm.js?2b0e:4495:1)
    at new Watcher (vue.runtime.esm.js?2b0e:4484:1)
    at mountComponent (vue.runtime.esm.js?2b0e:4088:1)
    at VueComponent.Vue.$mount (vue.runtime.esm.js?2b0e:8459:1)
    at init (vue.runtime.esm.js?2b0e:3137:1)
    at createComponent (vue.runtime.esm.js?2b0e:6022:1)
    at createElm (vue.runtime.esm.js?2b0e:5969:1)

Downgrading to v5 solves the issue

**Comment by richardtallent** [comment]
Version 6 requires Vue 3.
