### ISSUE TITLE
Requested feature (drag on date event)

### ISSUE THREAD

**Issue by vykimo** [richardtallent/vue-simple-calendar#134]
Hi,
Could you please add an event when drag start, drag over dates and drop on date?
With that, I'll be able to create new events with drag and an expand system.
I would be nice if you work on it as soon as possible !
Looking forward to hearing from you.
Regards

**Comment by richardtallent** [comment]
I like the idea! I'm not able to work on it presently, I'm about to be unplugged on vacation for a few weeks, but it's a good future improvement.

In the meantime, there is a "day click" event, so you can accomplish something similar by having the user click the start date and then the end date to set the date range... similar to how most hotel and airline reservation sites work. (Drag and drop also works differently on mobile, but clicks work the same way on both.)

**Comment by vykimo** [comment]
In fact I would like to do like that : 
https://clickermonkey.github.io/dayspan-vuetify/example/ (try to drag and drop new event)
Maybe if I do a Merge Request you could accept it?
If no, could you tell me when you'll be back from vacation?

**Comment by richardtallent** [comment]
Hi @vykimo - I've not been doing much OSS work, very busy with other things, but today I was able to get the changes you requested added, along with some other minor updates and bug fixes. Thanks!
