### ISSUE TITLE
28th Oct Start Date

### ISSUE THREAD

**Issue by ghost** [richardtallent/vue-simple-calendar#135]
If an event starts on the 28th of Oct it does not show up on the Calander view until the 19th.

This can be seen in the demo here: https://www.tallent.us/vue-simple-calendar/

![image](https://user-images.githubusercontent.com/56260803/66314722-56ffe100-e90c-11e9-9d28-8b64b742ca1e.png)

**Comment by richardtallent** [comment]
This appears to be a timezone issue -- probably an issue with the demo's v-model binding to an input date field rather than an issue with the calendar control itself. 

Can you tell me which time zone you are in and which browser you tested?

**Comment by SamS1984** [comment]
Using Chrome Version 76.0.3809.132 (Official Build) (64-bit)
My timezone is GMT and currently, BST the clocks here switch on the 28th, so the hour 00:00:00 on the 28th may not exist?

**Comment by richardtallent** [comment]
Ah, yes, this could be an issue related to clock changes. Here in the states, the clocks actually change at 02:00 rather than at midnight, which side-steps some date-related issues. Either way, this sounds like a rather rare edge case that will take some effort to track down. Leaving it open for now.

**Comment by richardtallent** [comment]
This was the same as #150, so between the two reports, I was able to figure out a fix. I'm about to release a new version that will fix this. Sorry it's taken so long -- real job and real life have taken over OSS time.
