### ISSUE TITLE
How in vue-simple-calendar show item long description as rendered html

### ISSUE THREAD

**Issue by PetroGromovo** [richardtallent/vue-simple-calendar#136]
In my Laravel 5.8 / "vue": "^2.6.10"/ app I added "vue-simple-calendar": "^4.2.2" component and search way to show short title in event cell and item long description when mouse is over (not clicked) event. Can this long description be rendered html code? Please example...

Thanks!

**Comment by richardtallent** [comment]
Currently, the best option would be to use the event slot to provide your own HTML for both the event as shown on the calendar and whatever other pop-up content you want to show on hover, and the handling of the mouse events.

A future enhancement could be for the component to raise mouse over/out events when an item is hovered (similar to how it currently sets the onhover class).

Another option would be to embed the hover HTML div to show the description in the event title, and use CSS to hide the div except when the event is :hover.

I would throw together an example for you, but my computer is currently broken, I’m wiring this on my phone.

**Comment by PetroGromovo** [comment]
richardtallent, you promised to provide some example . I still wait...

Thanks!

**Comment by richardtallent** [comment]
I believe the translation you are reading may be incorrect. I didn’t promise an example, I explained how to do what you’re looking to do.

I still don’t have a working computer right now, and have no reasonable way to create an example using my phone.

**Comment by PetroGromovo** [comment]
Hello,
Hope you are well and repaired you computer.
Could you please to provide an example to show short title in event cell and item long description when mouse is over (not clicked) event ?
I tried to follow your description, but that seems too complicated for me...

Thanks!

**Comment by richardtallent** [comment]
I've done some testing, and using `:hover` and extra HTML within the calendar item's "title" property will not work -- the event's div will clip any child content, so there's no way for the event element to *contain* the tooltip. This also means that the `slot` approach I described won't work, for the same reason.

The only way I can think of to do this now would be for you to make your own tooltip `div` element that renders the long description, and use absolute positioning to place it next to the event being hovered.

The newest version of this component, 4.3.2, optionally allows you to set the `doEmitItemMouseEvents` prop to `true`. This will tell the component to fire Vue events `item-mouseenter` and `item-mouseleave` when the user's mouse enters or leaves a calendar item. The Vue event will contain both the event hovered over and the original MouseEvent (which contains the mouse position and DOM element hovered over). You can listen for these events and use them to update your tooltip to render the correct description and move it to the correct location on screen. I will not be able to volunteer to create an example of this for you.
