### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by jd-0001** [richardtallent/vue-simple-calendar#138]
Hello Thanks for great calendar.

I was using this for long time. However, I would like to implement RTL version of your plugin.
However, using RTL webpack plugin I am able to render dates in RTL but events are still rendered according to LTR.
Please let me know if you are planning to add RTL support.
If you have something for me or suggestion I may give PR for this(If i am experieced enough to undestand your code).

Big Thanks :blush:

**Comment by richardtallent** [comment]
Hi! I'm afraid I'm not well-versed in how RTL languages would differ when it comes to a calendar grid. I did a quick Google, and from what I can tell so far, it's just a matter of ensuring the text-align and/or text-direction are set to follow the user's browser preferences.

If I'm missing something critical in making RTL function properly, please provide a screen shot of any calendar that does things the way the average RTL reader would expect.

**Comment by jd-0001** [comment]
Hello @richardtallent,
Thanks for your resopnse. Below is SS for LTR which shows event starting from date **3 to 7**
![LTR-event](https://user-images.githubusercontent.com/47495003/68989012-c00d3980-0866-11ea-9479-17d2f8b32569.png)
Here's Same event in RTL which shows **5 to 9**(incorrect)
![RTL-event](https://user-images.githubusercontent.com/47495003/68989019-d4e9cd00-0866-11ea-9194-66f312cc5e95.png)

According to your descriptiom for RTL you are completely right. It works that way but event created using JS is not reflecting accroding to RTL as it is positioned using top left.

For testing you can check our live demo [here](https://pixinvent.com/demo/vuexy-vuejs-admin-dashboard-template/demo-1/apps/calendar/vue-simple-calendar).

Thanks for awesome package :blush:

**Comment by richardtallent** [comment]
Thanks!

Yes, the events are positioned with top/left (which is static), but the days are populated using flex-start (which is RTL-sensitive).

From a little Googling, it appears that Gregorian calendars for RTL languages generally still order the days left to right. Is that your experience?

If so, this might be a quick fix to force the `direction` on the "week" divs. The caveat would be that days would inherit the same setting, and while there's not much "day" content by default, that is used to display holidays, and the forced LTR would also impact people using day slots.

In CSS4, we could just do something like `.cv-week:dir(rtl) { flex-direction: row-reverse; }`, but that's only available on Firefox so far.

**Comment by richardtallent** [comment]
Ah! If I'm understanding this correctly, we can then set `direction: initial` on the `cv-day` and `cv-event` classes to return them to the user's locale-based preference. Haven't tried yet, just making a note.

**Comment by jd-0001** [comment]
@richardtallent I will check your inputs and get back to you.

**Comment by richardtallent** [comment]
I applied this fix in 4.3.2, and based on a quick test here, I believe it worked! Please confirm and re-open if there are still any RTL layout issues.
