### ISSUE TITLE
How to show dialog before drop on date

### ISSUE THREAD

**Issue by li-liez** [richardtallent/vue-simple-calendar#141]
How to show dialog before drop date in event @drop-on-date like in live demo ? 
Thanks.

**Comment by richardtallent** [comment]
The component does not include any sort of dialog or other application functions, it's **just** a calendar grid component. Everything else (state management, event creation and editing, etc.) would need to be developed by the user.

The live demo is just a very minimal example to demonstrate some interaction with the calendar. The code for it is published in its own repo, you can see it there.
