### ISSUE TITLE
Days can expand vertically based on content

### ISSUE THREAD

**Issue by joecodecreations** [richardtallent/vue-simple-calendar#144]
I'm looking to find a calendar that can expand vertically on the week row based on event content. 

It looks like this is absolute positioning the events and therefore unable to adjust the sizing of the day's heights based on the events in the calendar. 

I might add this feature if you'll accept it and if it doesn't already allow this. I might need to check other libraries first due to project time constraints however. 

Is there a way to do this currently?

Thanks!

**Comment by richardtallent** [comment]
Hi Joe,

Arbitrary or automatic height of events is not something I would be interested in adding, as it would require changes that would break two core features: (1) the aesthetics of a consistently-spaced grid, and (2) the ability to have events that span more than one day and that "stack" where possible.

There are various workarounds you can use, if you're willing to override some CSS and you *don't* have events spanning across multiple days. Please see the following similar issues for more background:

#119 
#97 
#61 
#58 

Thanks!
