### ISSUE TITLE
change color for non disabled days

### ISSUE THREAD

**Issue by rrd108** [richardtallent/vue-simple-calendar#154]
Hi, How do I cange the color of non disabled days?

**Comment by richardtallent** [comment]
Hi @rrd108,

The only dates that would be "disabled" are past or future dates if you use the `disablePast` and/or `disableFuture` feature. These attributes already have classes associated with them. So, to change the color of "non-disabled" dates, you would just change the color of the dates using CSS, and exclude dates that have the `past` and/or `future` classes (whichever of those is disabled).
