### ISSUE TITLE
How to have dynamic top position for events slot

### ISSUE THREAD

**Issue by FrancescoMussi** [richardtallent/vue-simple-calendar#155]
I am using slot to display custom events.
However when using slot the dynamic vertical positioning is not applied.

I am referring to this funciton:

```
getItemTop(e) {
	// Compute the top position of the item based on its assigned row within the given week.
	const r = e.eventRow
	const h = this.eventContentHeight
	const b = this.eventBorderHeight
	return `calc(${this.eventTop} + ${r}*${h} + ${r}*${b})`
},
```

It's applied properly only when not using event slot. <br>
Otherwise the events are on top of each other.

Do you know how this can be fixed?

Thanks!

**Comment by richardtallent** [comment]
Hi @FrancescoMussi,

The results of `getItemTop()` are passed to your slot in the `top` property. You should be able to just retrieve that value and apply it in the `style` attribute of your top-level markup in your slot.
