### ISSUE TITLE
"events" property mislabeled as "items" in readme

### ISSUE THREAD

**Issue by njromano** [richardtallent/vue-simple-calendar#156]
Hi all, new here.

I noticed that the readme speaks about the `items` property:
>Items (Scheduled events to show on the calendar)
>items - An array of items to show on the calendar. See Calendar Item Properties below for more details.
>enableDragDrop - If true, items are draggable, and dragging and dropping them emits events you can catch and respond to. >Default is false. (Note: since this is a Boolean value, you should use v-bind on the attribute.)

However in the version npm installed for me, 4.4.0, this property appears to be `events`. Should I or someone update the readme?

**Comment by njromano** [comment]
nevermind, brain fart. saw the top of the readme

**Comment by richardtallent** [comment]
Hi! Just wanted to let you know that version 5.0 is now out, so the change from events to items is now "live."
