### ISSUE TITLE
toBeContinued class not being applied on 8 day event

### ISSUE THREAD

**Issue by houseoftech** [richardtallent/vue-simple-calendar#16]
Take a look at the Multi-day event on the demo. The dayDiff() function is calculating 12 - 5 = 7 so it thinks it doesn't spill over to the next week. If times were included it would still break because of the now included round() function. For now it would work to change the condition to >= 7.

**Comment by richardtallent** [comment]
Thanks, all fixed! I have a suspicion that I wrote the original code while using March as my example, and DST changed on March 12 (i.e., within the "Multi-day event", and not noticing the DST bug then led me to the bad logic I had there.

Released and published as 1.5.3...
