### ISSUE TITLE
Vertical design (for the wish list)

### ISSUE THREAD

**Issue by averied** [richardtallent/vue-simple-calendar#160]
Normally calendars have an horizontal design, but it would be nice to support a vertical design as well, like a list. For example:

![image](https://user-images.githubusercontent.com/10140930/90503522-76c87e00-e147-11ea-954a-9e76b510b418.png)

**Comment by narkoze** [comment]
https://github.com/richardtallent/vue-simple-calendar/issues/147

**Comment by richardtallent** [comment]
Hi @averied,

A vertical design would be out of scope for this project. I'm not even sure I've ever seen a calendar with such an orientation.
