### ISSUE TITLE
How do I disable specific days.

### ISSUE THREAD

**Issue by damoclesgil** [richardtallent/vue-simple-calendar#164]
How do I disable specific days. I need disable previous days based  from a specific day.
I was unable to use the `dateClasses` prop.
If you have an example, I would be very grateful.

Congratulations on the excellent work!

**Comment by richardtallent** [comment]
I've added an example for using `dateClasses` to the sample application.

This component doesn't really have a concept of "disabled" or "enabled" dates. It's up to you to decide what that means -- a different background color (`dateClasses` could help here), or not accepting drop events to that date, giving the user an error message if they click on that date.

**Comment by damoclesgil** [comment]
Thank you, that's what I wanted, to paint those days that were not activated.

Nice!
