### ISSUE TITLE
Week view, show times like google calendar

### ISSUE THREAD

**Issue by rolandso** [richardtallent/vue-simple-calendar#165]
The week view, is it possible to show times like a grid?
![Screen Shot 2021-01-06 at 09 01 49](https://user-images.githubusercontent.com/31401178/103739172-eb6c5e00-4ffd-11eb-9cfc-4d2928dc84b1.png)

**Comment by richardtallent** [comment]
Hi! This is mentioned in the readme under "What this component doesn't try to do". No such functionality will be built into this component, as it would require a significant amount of alternative markup and logic. Various bits and pieces of this component could certainly be used for such an effort, but it's not something I need or would use.
