### ISSUE TITLE
Testing and assistance with exports needed in version 6

### ISSUE THREAD

**Issue by richardtallent** [richardtallent/vue-simple-calendar#166]
I've upgraded the codebase to use Vue 3, TypeScript, and Vite for the dev server and build. This also allows us to have a native ES module build.

I could use some help in two areas:

1. I haven't figured out how to tell Vite to include the "./static/*.css" files (the optional themes) in the package.
2. Need to thoroughly test this before pushing it out there.

IE11 support is being removed in this version, so I'm not looking for testing in that area, just in making sure I haven't broken Vue 2 compatibility, theming, external access to the CalendarMath functions, etc., and to properly document any changes needed for migration.

**Comment by richardtallent** [comment]
**Update:**

1. The default CSS is not injected due to an undocumented behavior in Vite that is intended to improve SSR compatibility (https://github.com/vitejs/vite/issues/1579). I'm hoping a workaround will be found so everyone doesn't have to start importing the default CSS separately from the component.

2. I have a lead on getting the TypeScript declarations to be built and included with the component. Just haven't had a chance to play with it yet.

Help with making this SSR-compatible would be appreciated! I don't use Nuxt, so ideally any code changes needed should (a) have automated tests to go along with them so I don't break anything accidentally in the future and (b) should not diminish the developer experience for users (like me) who *don't* use SSR.

**Comment by supermarcos** [comment]
Hi @richardtallent I know you closed this one for quite a long, but what was the solution? I'm surprised I found this issue myself still in March 2022. To me it's a no-brainier: we need to have both worlds supported.

**Comment by richardtallent** [comment]
I’m not sure what the status of this component is wrt Nuxt compatibility. It’s not a tool I use, so I have to rely on the user community to tell me where the issues are (if there are any).

On the TypeScript front, the type declarations are included with the package, so I think we’re all good there.

As for CSS, I’m still underwhelmed by the “official” solution being to have users import CSS files directly from node_modules, but I haven’t seen a good alternative yet.
