### ISSUE TITLE
Just CalendarHeader

### ISSUE THREAD

**Issue by ibadass** [richardtallent/vue-simple-calendar#167]
Hi,

Great library ! Very userful and pretty !

Is it possible to display just the CalendarHeader and not the Grid ?

Thanks in advance.

**Comment by richardtallent** [comment]
Hi! I've not tried to use it by itself, but it is an independent component, so you would just need to feed it a compatible `headerProps` property. That property takes in an `IHeaderProps` object, but really only uses the following properties:

- previousYear
- nextYear
- previousPeriod
- nextPeriod
- currentPeriod
- currentPeriodLabel
- periodLabel

(The other properties of `IHeaderProps` are there in case someone wants to replace the header with their own header component and needs access to more information.)

**Comment by ibadass** [comment]
Thanks for your answer, but I'm able to implement, could you help me ?
