### ISSUE TITLE
Working with latest version in a Vue 2 project

### ISSUE THREAD

**Issue by mtalhabalci** [richardtallent/vue-simple-calendar#169]
Hello,

I'm working with vue 2 and want to use the latest calendar version.
As i see from sample latest version uses vue 3. There are break changes with vue 2 and 3 and i dont want to migrate before the Migration Build is announced.
I've tried older versions of calendar and there were no problems.

So my question is; how can i use the latest version in a vue 2 project.

This is my cli when i run the code;
![error](https://user-images.githubusercontent.com/47703652/116200516-190e1c00-a741-11eb-931e-34612efba026.PNG)

and this is the error i get in browser dev tools.
![object is not a func](https://user-images.githubusercontent.com/47703652/116200554-26c3a180-a741-11eb-91c2-04ebd0c68c9d.PNG)

Could you please help.
Thanks.

**Comment by richardtallent** [comment]
Hi @mtalhabalci,

Version 6 is not compatible with Vue 2. I *really* wish the Vue team had spent more time making Vue 3 components backward-compatible, but it's just not possible as far as I'm aware.

I wanted to wait for the migration build as well, but I finally gave up waiting (months ago) and upgraded all of my projects (personal and work) to Vue 3 and Vite. It was a bit of a pain, but worth it.

The last version for Vue 2 is 5.0.1:

https://www.npmjs.com/package/vue-simple-calendar/v/5.0.1

There won't be any further changes for that branch.

**Comment by mtalhabalci** [comment]
Thanks for the reply.

I think i'll speed up my way to vue 3.
Greetings.
