### ISSUE TITLE
.past and .future classes seem backwards

### ISSUE THREAD

**Issue by houseoftech** [richardtallent/vue-simple-calendar#17]
It's currently November and when clicking back to October it adds the class `future` and when clicking forward to December it adds class `past`. Seems like it should be the other way around, no?

Just need to swap the comparisons on the isPastMonth() and isFutureMonth() functions.

**Comment by richardtallent** [comment]
Dang it, where’s a “slap my forehead” emoji when you need one? Bug confirmed, will fix.

Clearly I need to add some unit tests to the mixin...

**Comment by richardtallent** [comment]
Corrected in the master branch, will hold off on another point release in case any other little issues crop up as you're testing it... thanks!
