### ISSUE TITLE
Hide Scrollbar Option

### ISSUE THREAD

**Issue by mtalhabalci** [richardtallent/vue-simple-calendar#171]
Hello,

In previous versions scrollbar for a day didnt exist.

As the scrollbar appears the symmetry corrupts.

So my question is is there a way to hide the scroll?

Sharing the image to show the corruption.
![calendar scroll issue](https://user-images.githubusercontent.com/47703652/116567787-9dfb6000-a910-11eb-8cf2-d4039f0b402b.PNG)

Greetings.

**Comment by richardtallent** [comment]
Visibility of scrollbars (and thus how content is impacted) is determined by your operating system and browser.

I'm usually working on a Mac, and in all browsers I use, the scrollbars overlay the content and only show up when scrolling.

Looks like you're using Windows. There may be a browser-specific CSS rule you can use to either hide the scrollbar entirely, or override the styling so it doesn't impact your content. Another option would be to *always* show the scrollbar on each week, but use CSS to hide the "track." That will effectively leave you with a margin on the right side of every week, but at least all weeks will be the same width.

**Comment by iAminaDarwish** [comment]
I have two projects using vue-simple-calendar 
the old one have the nice scrolling on the day 
the new one have the issue described by @mtalhabalci 
I am running both in windows  

for the new project  i added the following css and it worked 
.cv-weekdays::-webkit-scrollbar {
  width: 0px !important;
  cursor: pointer;
}
