### ISSUE TITLE
Remove border around the calendar

### ISSUE THREAD

**Issue by juangalbea** [richardtallent/vue-simple-calendar#172]
Is it possible to remove the border around the calendar without affecting the border of the inner tiles?

**Comment by juangalbea** [comment]
I found out,

this is the trick

.cv-weeks {
  border-width: 0 0 0 0;
}
.cv-day.dow0 {
  border-right: 0;
}
.cv-header-days {
  border-width: 0 0 0 0;
}
.cv-header-day {
  border-top: 0;
}
.cv-header-day.dow0 {
  border-right: 0;
}

**Comment by richardtallent** [comment]
Great, glad you figured it out! I've been a bit busy this week, just now trying to close out some questions and issues.
