### ISSUE TITLE
Add margin to the events

### ISSUE THREAD

**Issue by juangalbea** [richardtallent/vue-simple-calendar#173]
Is it possible to add margin left and right to the events?

<img width="721" alt="Screenshot 2021-04-29 at 17 09 31" src="https://user-images.githubusercontent.com/4815841/116582861-abfbb180-a90d-11eb-8871-78a7074747a0.png">

when I try to do it, the right margin doesn't work and it looks like this

<img width="659" alt="Screenshot 2021-04-29 at 17 11 36" src="https://user-images.githubusercontent.com/4815841/116583156-f67d2e00-a90d-11eb-8320-ad5471cf3c18.png">

**Comment by juangalbea** [comment]
I just realised how to do it, just checking the original code.
first reduce the span 2 rem if you want 1 rem margin right and 1 left
.cv-item.span1 {
  width: calc((100% / 7) - 2rem);
}

.cv-item.span2 {
  width: calc((200% / 7) - 2rem);
}

.cv-item.span3 {
  width: calc((300% / 7) - 2rem);
}

.cv-item.span4 {
  width: calc((400% / 7) - 2rem);
}

.cv-item.span5 {
  width: calc((500% / 7) - 2rem);
}

.cv-item.span6 {
  width: calc((600% / 7) - 2rem);
}

.cv-item.span7 {
  width: calc((700% / 7) - 2rem);
}

and second add 1 rem margin left

.theme-default .cv-item {
  margin-left: 1rem;
}

**Comment by richardtallent** [comment]
Margins on events certainly weren't considered in my default design, since there's already limited space for event titles (especially for one-day events or events that wrap close to the start or end of a week). Glad you figured out a workable solution!

**Comment by juangalbea** [comment]
Hi Richard, 

Thanks for getting back. I just realised that this way to add the margin has one issue, when the event is more than 1 week long, it also add the margins in Sunday and Monday, something that I wouldn't expect if I want to show continuity.

![Screenshot 2021-04-30 at 09 29 53](https://user-images.githubusercontent.com/4815841/116982293-85989600-acc0-11eb-838b-215dfe616142.png)

Any idea for this issue?

**Comment by juangalbea** [comment]
Hi Richard, 

Thanks for getting back. I just realised that this way to add the margin has one issue, when the event is more than 1 week long, it also add the margins in Sunday and Monday, something that I wouldn't expect if I want to show continuity.

![Screenshot 2021-04-30 at 09 29 53](https://user-images.githubusercontent.com/4815841/116983539-250a5880-acc2-11eb-9176-8d5e61eeb0e0.jpeg)

Any idea for this issue?
