### ISSUE TITLE
Margin on the event sides unless the event is more than 1 week.

### ISSUE THREAD

**Issue by juangalbea** [richardtallent/vue-simple-calendar#174]
Hi Richard,

Thanks for getting back. I just realised that this way to add the margin has one issue, when the event is more than 1 week long, it also add the margins in Sunday and Monday, something that I wouldn't expect if I want to show continuity.

![Screenshot 2021-04-30 at 09 29 53](https://user-images.githubusercontent.com/4815841/117724356-8909b100-b1db-11eb-8d23-47c6d08037f8.jpeg)

Any idea for this issue?

**Comment by richardtallent** [comment]
Hi @juangalbea,

There are special classes already added for events that are continued from the previous week, or that will spill over into the next week. Please refer to the documentation and adjust the margins as desired for those special cases.
