### ISSUE TITLE
style the whole event when hover

### ISSUE THREAD

**Issue by juangalbea** [richardtallent/vue-simple-calendar#175]
When I hover in one event that is more than one week longer, the hover effect only affect the part I am hovering, but not the whole event.

![Screenshot 2021-05-10 at 22 13 58](https://user-images.githubusercontent.com/4815841/117725414-07b31e00-b1dd-11eb-900f-0cc61f10eec3.png)

In "Search Summit" we can see how the top part it hover and styled with darker blue, but the bottom part of the event doesn't style and keeps the light blue

**Comment by richardtallent** [comment]
This is a consequence of the fact that this component uses native CSS hover pseudo-classes, not JavaScript-based hovering. You can implement your own hover logic by using the `item-mouseenter` and `item-mouseleave` events to manually manipulate the item's classes.
