### ISSUE TITLE
Item style property not functioning. @V5.0.1

### ISSUE THREAD

**Issue by NickyAlfEdge** [richardtallent/vue-simple-calendar#176]
I'm currently trying to apply different background-color stylings to particular kinds of items I am adding to the calendar, this however doesn't appear to be working.

A collection of objects in the suggested format are being supplied to the calendar and bound through the items property, with everything working fine, with the exception of the stylings I am passing through the objects style property. 

As an example, this is the format of my items.

```javascript
items: [
  {
    id: 1,
    startDate: '2021-05-15',
    endDate: '2021-05-15',
    title: 'Example Event 1',
    style: 'background-colour: #F26B5B;'
  }
],
```
Is this an actual issue, or am I being an idiot? 

Any help on this matter would be much appreciated.

Many thanks.

**Comment by NickyAlfEdge** [comment]
Please ignore this issue. I revisited it after a while and realised that I was indeed, being an idiot. I had been providing the British English spelling of 'colour', when it should be 'color'...

**Comment by richardtallent** [comment]
Ah! lol... I just had a moment to drop in and see what might be the issue, glad it's resolved!

Version 6 is out, BTW... I won't be making additional changes to 5, since I've gotten quite spoiled on Vite and Vue 3. :)
