### ISSUE TITLE
Dynamic position for items

### ISSUE THREAD

**Issue by PonchRobles** [richardtallent/vue-simple-calendar#178]
Hello how things are going!

Currently I have a problem where I am customizing to show the element, and the problem I find is that the dynamic position turns out to be the same for each element which causes the elements to overlap.
I have been supporting myself with the documentation and with some resolved issues but I have not been able to solve this problem.

My Env:
- Laravel ^8.12
- Vue ^3.0.11
- Tailwind Css ^2.0.2
- vue-simple-calendar ^6.0.1

This issue seems to relate to what I am trying to solve, but it doesn't work for me. #155 

Case item custom: 
 ```
<template v-slot:item="{ value: item, top }">
    <div class="cv-item bg-yellow-50 border-l-4 border-yellow-400 p-4" :style="`top:${top}`">
        <div class="flex">
            <div class="ml-3">
                <p class="text-sm text-yellow-700">
                    {{ item.title }}
                </p>
            </div>
        </div>
    </div>
</template>
```
In brwoser: 
![image](https://user-images.githubusercontent.com/18694132/119583798-f9443500-bd8c-11eb-8ab2-597bb2fd298a.png)

When I see it in the inspector:
![image](https://user-images.githubusercontent.com/18694132/119583891-2f81b480-bd8d-11eb-8ba4-9c37d9cebdd9.png)

Anyone have any ideas?
Thank you very much and greetings!
Sorry for my English is not my first language.

**Comment by richardtallent** [comment]
This seems to be an issue computing itemRow for each event.

Can you create a version of your calendar component and dataset that reproduces the issue and share it? I'm not seeing anything wrong in the component code.

**Comment by PonchRobles** [comment]
@richardtallent 

> This seems to be an issue computing itemRow for each event.
> 
> Can you create a version of your calendar component and dataset that reproduces the issue and share it? I'm not seeing anything wrong in the component code.

I literally did what I am using, forgot to mention that I had some trouble importing the component styles so I had to put them directly into the CustomCalendar component, not sure this creates the problem.
[Example On CodeSandBox](https://codesandbox.io/s/vue-simple-calendar-example-4j6gr?file=/src/main.js)
[vue-simple-calendar-example-issue](https://4j6gr.csb.app/)

**Comment by erickcg** [comment]
I see the problem. You are ignoring the item.classes in the template. @PonchRobles 

Other thing that is causing problems is that the default values for: `
itemContentHeight: { type: String, default: "1.4em" },
itemBorderHeight: { type: String, default: "2px" },`

Are strings, and it creates a NaN result in CalendarView.vue: line 545. 
I fixed it changing it to 
`return`calc(${this.itemTop} + ${t}*${a}em + ${t}*${r}px)`

have a nice day!

**Comment by richardtallent** [comment]
Confirmed, @erickg is correct. The issue is that you aren't applying the `item.classes` to your item `<div>`. These classes are responsible for positioning both the top AND LEFT. Your events all start on different days, so their top position is correct, but their left position is never set, so they are overlapping.

@erickcg, string interpolation doesn't evaluate math expressions outside of `${}`, they just become part of the string. The multiplication done in this `calc()` string is done by CSS, and it is able to multiply a scalar value (`itemRow`) by values that have valid CSS units (`itemContentHeight` and `itemBorderHeight`). So, there's no need to split those props and do that math in JS.
