### ISSUE TITLE
Can this component display events within a day?

### ISSUE THREAD

**Issue by fbnlsr** [richardtallent/vue-simple-calendar#180]
I'm trying to display events as blocks, spanning vertically depending on their start end end time. Am I missing something or is it not feasable using `vue-simple-calendar`?

**Comment by richardtallent** [comment]
Hi! No, an "agenda"-style display (showing hours of the day vertically) is not supported. It would require a completely different template to render, and a lot of additional logic.

**Comment by fbnlsr** [comment]
Alright, thanks for the quick reply! :smiley:
