### ISSUE TITLE
Unable to Align Slotted Events Onto Calendar

### ISSUE THREAD

**Issue by WDC** [richardtallent/vue-simple-calendar#182]
I am using Vue 2 and SFC, and have a calendar like this:

```
<calendar-view
        :show-date="showDate"
        @click-item="openAppointment"
        @item-mouseenter="hoverItemEnter"
        @item-mouseleave="hoverItemLeave"
        :doEmitItemMouseEvents="true"
        :displayPeriodUom="filters.calendar_view"
        class="
          h-full h-screen
          text-sm
          holiday-us-traditional holiday-us-official
        "
        :items="items"
      >
        <calendar-view-header
          slot="header"
          slot-scope="t"
          :header-props="t.headerProps"
          @input="setShowDate"
        >
        </calendar-view-header>
        <div
          slot="item"
          slot-scope="i"
          :style="{ top: i.top }"
          :class="i.value.classes"
        >
          Test
        </div>
      </calendar-view>
```

I am trying to use a custom `slot` for the event rendering. I am binding the `value.classes` and the `top: calc(...)` parameters, but I still get output:
<img width="987" alt="image" src="https://user-images.githubusercontent.com/1221004/126535990-c948d7f5-0241-4a5a-ba84-07132df1eb92.png">
It appears that everything is working as expected with my `slot`, except for the horizontal placement of the Events on the grid. When I go to inspect one of my Events, I see this:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/1221004/126536170-4bb3dbc9-b786-4482-b1f6-c6a7f21d4f74.png">

Which tells me that the internal classes are being applied properly, but they are not being placed like the default Event template. When I remove my custom slot altogether and use the default template, the Events appear exactly where they should on the page (I added the custom class for the black background):
<img width="986" alt="image" src="https://user-images.githubusercontent.com/1221004/126536403-b451a524-e3d1-4690-8bed-ab509cec9d95.png">

What am I doing wrong with my `slot` such that the Events do not get placed properly on the x-axis like the default template does?

Thank you for such an excellent library!

**Comment by WDC** [comment]
It would appear adding the `.cv-item` class to the slotted `<div>` is the way to go.
**Before:**
```
        <div
          slot="item"
          slot-scope="i"
          :style="{ top: i.top }"
          :class="i.value.classes"
        >
          Test
        </div>
```

**After:**
```
        <div
          slot="item"
          slot-scope="i"
          :style="{ top: i.top }"
          :class="i.value.classes"
          class="cv-item"
        >
          Test
        </div>
```

If there is a better way to do this, I would love to hear it, but it appears that my issue is resolved.

**Comment by richardtallent** [comment]
Sounds like you figured it out! Been away on holiday, just got back.

I'm no longer using Vue 2 or older versions of this component that still support Vue 2, so if you have additional issues, please at least file with a minimal reproducible repository so me or someone can take a peek.
