### ISSUE TITLE
Missing "./dist/style.css" export in "vue-simple-calendar" package

### ISSUE THREAD

**Issue by pau-santesmasses** [richardtallent/vue-simple-calendar#185]
I'm getting this error when importing the styles from the package.

`import 'vue-simple-calendar/dist/style.css'`

`Missing "./dist/style.css" export in "vue-simple-calendar" package`

If I use a relative path, i.e. `../node_modules/vue-simple-calendar/dist/style.css`, the file is found and everything works.

**Comment by richardtallent** [comment]
Hi,

You're correct. Importing `vue-simple-calendar/dist/style.css` would only work from the project's root folder, and most people keep their JavaScript and components in a folder off of `./src`.

Here's the example app:

https://github.com/richardtallent/vue-simple-calendar-sample/blob/main/src/App.vue#L146

I've updated the documentation to hopefully make this more clear. Thanks!
