### ISSUE TITLE
Cannot read properties of null (reading 'isCE')

### ISSUE THREAD

**Issue by mpostman** [richardtallent/vue-simple-calendar#186]
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'isCE')
    at renderSlot (runtime-core.esm-bundler.js?9de3:6122)
    at Proxy.p.render (vue-simple-calendar.es.js?3a49:1)
    at renderComponentRoot (runtime-core.esm-bundler.js?9e79:761)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js?9e79:4529)
    at ReactiveEffect.run (reactivity.esm-bundler.js?0a2b:160)
    at setupRenderEffect (runtime-core.esm-bundler.js?9e79:4655)
    at mountComponent (runtime-core.esm-bundler.js?9e79:4438)
    at processComponent (runtime-core.esm-bundler.js?9e79:4396)
    at patch (runtime-core.esm-bundler.js?9e79:3991)
    at mountChildren (runtime-core.esm-bundler.js?9e79:4187)
    
```
<template>
  <div id="app">
    <h1>My Calendar</h1>
    <calendar-view
      :show-date="showDate"
      class="theme-default holiday-us-traditional holiday-us-official"
    >
      <template #header="{ headerProps }">
        <calendar-view-header
          :header-props="headerProps"
          @input="setShowDate"
        />
      </template>
    </calendar-view>
  </div>
</template>
<script>
import { CalendarView, CalendarViewHeader } from "vue-simple-calendar";
// import from "vue-simple-calendar/dist/style.css"
// // The next two lines are optional themes
// import from "vue-simple-calendar/static/css/default.css"
// import from "vue-simple-calendar/static/css/holidays-us.css"

export default {
  name: "app",
  data: function () {
    return { showDate: new Date() };
  },
  components: {
    CalendarView,
    CalendarViewHeader,
  },
  methods: {
    setShowDate(d) {
      this.showDate = d;
    },
  },
};
</script>
<style>
#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  color: #2c3e50;
  height: 67vh;
  width: 90vw;
  margin-left: auto;
  margin-right: auto;
}
</style>

```

- Quasar Framework v2.0.4
- Vue 3

**Comment by richardtallent** [comment]
Hi, @mpostman,

Please set up a minimal reproducible codebase demonstrating the problem. I can't even fathom what the issue might be from this post, or even if it has anything to do with this component.

**Comment by w20k** [comment]
Hi,
I'm having the same issue, haven't found the exact cause, but it's related to Vite.js chanking/caching. 

Removing 'vue-simple-calender' from Vite.js cache solves this issue.

_vite.config.ts_
```
exclude: [
        'vue-simple-calendar',
],
```

**Comment by richardtallent** [comment]
Hi, @w20k,

Please set up a minimal reproducible codebase demonstrating the problem.

**Comment by w20k** [comment]
Hm... seems like something is related to our project plugins or dependencies. Will try to look at it today.

Couldn't reproduce on the empty project based on the `vitesse template` + `vue-simple-calendar`.
