### ISSUE TITLE
Trouble with item slot drag handler

### ISSUE THREAD

**Issue by Kaibu** [richardtallent/vue-simple-calendar#187]
I'm having issues with using the item slot, everything works besides passing "up" the currently the dragged item.

From my understanding, accessing `currentDragItem` is not possible from within the slot scope.
The `onDragItemStart` method is also not passed on to the slot, nor does the scope above the slot listen for any drag-start events.
But this functionality is required for the `drop-on-date` handler to correcly propagate the event with the item id.

I have created a component for the slot named `meal-plan card` and set it as the slot, passing all the given slot props.

```
 <template #item="{ value, weekStartDate, top }">
            <meal-plan-card :value="value" :week-start-date="weekStartDate" :top="top"/>
          </template>
```

```
<template>
  <div class="card" :key="value.id" :draggable="true" :style="`top:${top}`"
       @dragstart="onDragItemStart(value, $event)"
       @click.stop="onClickItem(value, $event)"
       :aria-grabbed="value == currentDragItem">
    <div class="card-header">
    </div>
    <div class="card-body">
    </div>
  </div>
</template>
```

I can implement `onDragItemStart` in my component but can't pass that up to the main calender component.

Is that a bug or is my understanding of slots somehow wrong?

**Comment by Kaibu** [comment]
I've added this code snippet to CalenderView.vue and pass events from my slotted component onto root.

This is of course a hacky fix but may help you understanding the issue.

```
created() {
    this.$root.$on('dragUpdate', (item, e) => {
      this.onDragItemStart(item, e)
    })
    this.$root.$on('click-item', (item, e) => {
      this.onClickItem(item, e)
    })
  },
```

**Comment by richardtallent** [comment]
Hi,

Yes, you're correct. `currentDragItem` is internal state for the calendar component, so it shouldn't be directly modified by the slot, and `onDragItemStart` is only intended to handle the component's own window events, not ones initiated by the user dragging elements in a slot.

Fortunately, the calendar component doesn't need to even know that your event slot is even being dragged. Any draggable element can be dropped on a date in the calendar, and the calendar will emit the `drop-on-date` event.

The payload for this event won't have the calendar item as the first argument (it will be `null`), but it will still pass the Date dropped on as the second argument.

So, your `MealPlanCard` component in your slot should emit an event for `@dragstart` to your parent component, and the parent should update its state to keep drag of the item being dragged. Then, when the parent component captures the `drag-on-date` event from the calendar, it doesn't need to rely on the calendar component to know which item is being dragged.

By doing it this way, you don't have to drag items *from* the calendar (i.e., your item slot) to drop them *into* the calendar. For example, you could have a set of pre-defined meals in another component entirely, and drops them into the calendar to create an event. Or you could drag events from one calendar to another.

Here's an example -- it's late, there are very likely some errors or missing bits:

```
<template>
   <calendar-view ... @drop-on-date="handleEventDrop">
       <template #item="{ value, weekStartDate, top }">
           <meal-plan-card :value="value" :week-start-date="weekStartDate" :top="top" @drag-started="setMyCurrentDragItem(value)" />
       </template>
    </calendar-view>
</template>
<script>
export default {
    data: () => ({ currentDragItem: null }),
    methods: {
        setMyCurrentDragItem(value) { this.currentDragItem = value },
        handleEventDrop(_, targetDate) {
            this.currentDragItem.startDate = targetDate
            this.currentDragItem = null
        }
    }
}
</script>

I do see a potential for a minor accessibility issue (lack of `aria-dropeffect` attribute on the date element) when someone implements their own slot drag-and-drop, but I think that could be resolved fairly easily. I'll have to keep that in mind for a future release, it would probably require a new boolean property to tell the component that a drag it isn't responsible for is in progress.

**Comment by Kaibu** [comment]
Thanks for the clarification, your solution works and is of course much better.

I was looking for a "all-vue slot" type of solution for handling this but keeping track of the dragged item myself works aswell.
