### ISSUE TITLE
Align times on week and day view

### ISSUE THREAD

**Issue by djcaesar9114** [richardtallent/vue-simple-calendar#188]
For the moment events are stacked.
It would be great to have an Y axis showing the hours (0:00 to 24:00) so that events would be placed only between the hours they are scheduled..
A slot for a full-day event could be place on top:

![image](https://user-images.githubusercontent.com/19804251/133324421-ba23544d-74f5-44f3-8fbd-15255d29e61d.png)

**Comment by richardtallent** [comment]
Hi,

There will be no "agenda" view (time-of-day grid). Adding this view would require too much additional complexity. You could certainly build one separately that reuses pieces of the logic in this component, but the template would need to be very different.

**Comment by djcaesar9114** [comment]
OK I understand. Great job anyway, I love your work! :)

**Comment by primoashbee** [comment]
@djcaesar9114 you found a way to achieve what you mentioned?

**Comment by djcaesar9114** [comment]
> @djcaesar9114 did you found a way to achieve what you mentioned?

Not yet, I may spend some time on it later, though.
