### ISSUE TITLE
Is it possible to use VueSimpleCalendar with SSR?

### ISSUE THREAD

**Issue by amkatyshev** [richardtallent/vue-simple-calendar#191]
I'm using Nuxt v2.15.8.
Please, maybe anybody use this plugin with Nuxt? Or could someone tell me how to correctly connect CalendarView to the page?
When switching from page to page by nuxt-links, everything works correctly. But when I reload the page with Calendar I got error with message "document is not defined"? 

<img width="1363" alt="Снимок экрана 2021-10-31 в 12 18 04" src="https://user-images.githubusercontent.com/36438365/139575915-afc78630-b75c-4144-9de5-5c9e292fabfb.png">

How can I solve this problem?

**Comment by richardtallent** [comment]
Unfortunately, I've never had a reason to use SSR, so I don't have a clue what the issue could be. :(

**Comment by amkatyshev** [comment]
I've never taken part in plugin development, but I want to help with this issue :)
Some plugins have a separation between styles and js in Vue Component.
I think, styles described in "styles scoped" block need to move to another CSS-file. In this case, Vue Component must not contain any CSS code. I think it will help to avoid using vue-style-loader, which can conflict with SSR :)

**Comment by amkatyshev** [comment]
Sometimes developers create additional Component without css, which contains exactly the same component code but without CSS.
It will need to use component as is (source component) and use as Server Side Component (additional component)

**Comment by richardtallent** [comment]
Since this component is compiled via vite rather than webpack, CSS is already split into a separate file that has to be manually imported. (Also, none of the styles here are scoped, since that makes them more difficult to override for theming.) We aren't using vue-style-loader.

So, I don't think that would be the issue in this case.

**Comment by amkatyshev** [comment]
Oh, I didn't tell about something...
I'm telling now about 5x version of Calendar :)
It's under Vue 2

**Comment by richardtallent** [comment]
This is open source, I can't support old versions of the component. Please feel free to open another issue if the current version under Vue 3 exhibits a similar issue.
