### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by alexsantm2019** [richardtallent/vue-simple-calendar#193]
Hi,
I have installed the calendar component in vue 2. I have followed the instructions in the repository, but when I refresh the page I have the following error:

Object(...) is not a function

Suddenly can you help me indicating what I should do to correct it?

Thanks a lot.

**Comment by nivaldomcj** [comment]
@alexsantm2019 

Had the same issue. As is stated on README, in version 6 the component has migrated to Vue 3 so you should install a version < 6. I did it here in a project that I'm working on (that uses Vue 2) and it worked for me.

**Comment by SmallTeddy** [comment]
我遇到了相同的问题
![image](https://user-images.githubusercontent.com/61453917/150903044-55b86fe9-7995-431a-a79f-a1c9789656e7.png)
![image](https://user-images.githubusercontent.com/61453917/150903080-070581b2-a98b-4542-967f-0b65eb46f8a1.png)
![image](https://user-images.githubusercontent.com/61453917/150903131-6463f71b-ab9f-4f2f-ae99-f9982ee179bb.png)

**Comment by richardtallent** [comment]
yeah... uhm... I'm not going to be able to debug that comment.

@nivaldomcj is correct... we're Vue 3 all the way now! Only older versions support Vue 2, and I'm not able to maintain or provide support for the old versions.
