### ISSUE TITLE
Header days are rendering in a wrong order after user prop startingDayOfWeek="0|1|2|3|4|5|6" 

### ISSUE THREAD

**Issue by blogui91** [richardtallent/vue-simple-calendar#196]
Hello!
I really love this component! But I'm have an issue :(. I have the following code:

<img width="876" alt="image" src="https://user-images.githubusercontent.com/5723380/155846653-fd2e11ab-9562-4096-800e-1c0eadaffcb5.png">

But when the calendar is rendered the header days are in a wrong order :(  It supposed to start from Monday but is starting from Wednesday and also Saturday appears next to Wed

![image](https://user-images.githubusercontent.com/5723380/155846711-10ec9b33-4e7b-4bee-bb6d-2f2ab493a76d.png)

I'm looking forward in case you need some additional information.

Thank you

**Comment by blogui91** [comment]
I could solved, I am passing the prop value as string but I have to use an integer instead 

startingDayOfWeek="1" // wrong
:startingDayOfWeek="1" // correct

I leave this log just in case someone has the same issue.

**Comment by richardtallent** [comment]
Ah! Yes, Vue doesn't convert props to their declared types. Glad you figured it out! I recommend using the Volar extension if you're using Visual Studio Code, it will flag issues like this where you need data binding (`:foo=`) and are missing the colon.
