### ISSUE TITLE
Bug when using item specific classes

### ISSUE THREAD

**Issue by ChristianRiedl** [richardtallent/vue-simple-calendar#209]
In your sample you specify a specific color for an item : 

     {
		id: "e6",
		startDate: thisMonth(29),
		title: "Same day 2",
		classes: "orange",
    }

but the item is shown in default color. Inspecting the created HTML I see that the reason is a wrong class name.

    <div draggable="true" aria-grabbed="false" class="o r a n g e offset1 span1 cv-item" 

I have one more please : Please make **ICalendarItem** and **IHeaderProps** items available for Typescript (include them in main.d.ts).

**Anyhow - Vue Simple Calendar is exactly what I need !!**

**Comment by SincerelyUnique** [comment]
![image](https://user-images.githubusercontent.com/16249717/186112671-c31fb4ae-af15-44b8-b2d9-f55189f88e77.png)
![image](https://user-images.githubusercontent.com/16249717/186113386-5aad5da0-c8cb-4f3e-92b6-cf18073f61d6.png)

Hi @ChristianRiedl 

For me, the class name is correct, and I can change the class, please reference to https://github.com/richardtallent/vue-simple-calendar#calendar-item-properties, and below is my code, you can refer to it 

```
               for(let i=0;i<returnedDataList.length;i++){
                    returnedDataList[i]['startDate'] = new Date(returnedDataList[i]['schstartdate'])
                    returnedDataList[i]['endDate'] = new Date(returnedDataList[i]['schenddate'])

                    if(returnedDataList[i]['status'] === 'Closed'){
                        returnedDataList[i]['classes'] = 'purple'
                    }else{
                        returnedDataList[i]['classes'] = 'orange'
                    }
                    //returnedDataList[i]['style'] = 'background-color: #0281B0'     // another usage
                    returnedDataList[i]['title'] = returnedDataList[i]['title']
                    returnedDataList[i]['url'] = 'xxx'
                    returnedDataList[i]['id'] = returnedDataList[i]['uuid']
                }
```

**Comment by ChristianRiedl** [comment]
Very strange. I can verify the problem also on your demopage https://tallent.us/vue-simple-calendar/?ref=madewithvuejs.com.

This and other items should be show with orange background. But all items have the same default background color :

				{
					id: "e10",
					startDate: this.thisMonth(29),
					title: "Same day 6",
					classes: "orange",
				},
I use Googe Chrome and using the dev tools I changed class "o r a n g e" for "Same day 2" item to "orange", than the item was shown with correct orange background.

 
![sample](https://user-images.githubusercontent.com/2470964/186123357-98fc9038-6480-452c-90e2-e7d074846ec3.png)

**Comment by richardtallent** [comment]
It appears my example is incorrect. I'm not at my computer, but IIRC,"classes" should be an array of strings, not a string.

I'm on the way to Burning Man and won't be online for several weeks. For this and any other issues, I can look over any PRs after I return.

**Comment by richardtallent** [comment]
Yes, it should be 'classes:["orange"]'. Otherwise the string "orange" gets split into an array of letters because JS is expecting an array.

**Comment by ChristianRiedl** [comment]
Ok, my integration was inspired by your sample. Thanks for quick and complete answer. I close the issue.
