### ISSUE TITLE
tooltip doesn't work

### ISSUE THREAD

**Issue by Luminus-developer** [richardtallent/vue-simple-calendar#212]
Hi!
The tooltip doesn't replace the title. 
The line of your code is 
**title: o.tooltip || o.title,** 
I think you must replace it with :
**title: o.originalItem.tooltip || o.title,**
Have a nice Day
Wal

**Comment by richardtallent** [comment]
Thanks, I'm working on a fix for the next version for this.

**Comment by richardtallent** [comment]
Thanks, this has been addressed in 6.1.0 and 6.2.0, released today.
