### ISSUE TITLE
Misaligned row in demo

### ISSUE THREAD

**Issue by devmount** [richardtallent/vue-simple-calendar#213]
Thanks for this great calendar view! I found that the current demo page shows misaligned cells in week 44 for October 2022:

![image](https://user-images.githubusercontent.com/5441654/194496989-88e313f3-0b6b-482c-a65d-7c985fa494e3.png)

I tested this on Opera on Windows 10. I suspect this is caused by the Windows scrollbar.

**Comment by richardtallent** [comment]
Note: Opera is **not supported**.

That said, I am seeing something similar now in Chrome on Mac OS, so I'm filing this as a bug.

**Comment by richardtallent** [comment]
Thanks, this has been addressed in 6.1.0 and 6.2.0, released today. However the fix relies on webkit-specific CSS rules, so it may still not hide the scrollbar properly in Opera.

**Comment by devmount** [comment]
Thank you @richardtallent - it works now on Opera too (which is webkit based for years now)! Thanks again 🙏🏻

**Comment by richardtallent** [comment]
Oh! I forgot that Opera joined the Dark Side :)
