### ISSUE TITLE
Error of import

### ISSUE THREAD

**Issue by djcaesar9114** [richardtallent/vue-simple-calendar#218]
Hello,
I'm following everything in the example correctly. My apps have always worked with vue-simple-calendar.
Actually I changed my NodeJS version to 19 and now I have this error:

```
 ERROR  Failed to compile with 1 error                                                                              17:20:54

 error  in ./src/components/outils/atelier/Calendar.vue?vue&type=script&lang=js

Module not found: Error: Package path ./dist/css/default.css is not exported from package /home/XXX/node_modules/vue-simple-calendar (see exports field in /home/XXX/node_modules/vue-simple-calendar/package.json)

```

`XXX` being the path to my project.

I kept the same lines I've been using for months:

```
import 'vue-simple-calendar/dist/style.css';
import 'vue-simple-calendar/dist/css/default.css';
```

I managed to solve this by adding this in the `package.json` file:

```

	"exports": {
		".": {
			"import": "./dist/vue-simple-calendar.mjs",
			"require": "./dist/vue-simple-calendar.umd.js"
		},
		"./dist/style.css": {
			"import": "./dist/style.css",
			"require": "./dist/style.css"
		},
		"./dist/css/default.css": {
			"import": "./dist/css/default.css",
			"require": "./dist/stcss/defaultyle.css"
		}
```

**Comment by richardtallent** [comment]
Hi! Sorry for the late reply, was dealing with COVID this week. I've added the static stylesheets to the exports list for 6.3.1, just published.

**Comment by djcaesar9114** [comment]
No problem, you give us a great open-source tool, there will never be any rush.
Take care, health and family is all that really matters.
Thanks for your answer ;)

**Comment by DaZOr93** [comment]
Problem still not solved, import import 'vue-simple-calendar/dist/css/default.css'; ok but 'vue-simple-calendar/dist/style.css' is not
