### ISSUE TITLE
Can't use named slots with camelCase like dayContent

### ISSUE THREAD

**Issue by namanagar** [richardtallent/vue-simple-calendar#224]
Seems like maybe it used to work, but I can't seem to write a `template #dayContent` or `template #day-content` or any other syntactical sugar equivalent since I believe slot names shouldn't contain uppercase characters?

https://stackoverflow.com/a/73065732

**Comment by richardtallent** [comment]
Thanks! I'll look into this. Sounds like it would require a breaking change.

**Comment by richardtallent** [comment]
Fixed in 7.0!
