### ISSUE TITLE
Week Numbers are off by 1

### ISSUE THREAD

**Issue by smilerz** [richardtallent/vue-simple-calendar#228]
The week starting Sept 4th is week 36.  The calendar displays week 37.

![image](https://github.com/richardtallent/vue-simple-calendar/assets/1808639/4a363118-6f53-49fd-af28-1c45948a8944)

**Comment by tomtjes** [comment]
This might be related. I noticed, when I create a cook log entry the time displays correctly, e.g. as
<img width="520" alt="Screenshot 2023-09-06 at 20 31 42" src="https://github.com/richardtallent/vue-simple-calendar/assets/7606307/d5e01c54-898b-4f20-9b8b-a04fa28a11d9">
Note, I'm not in the same timezone as the server. This shows when I look at the actual timestamp of the cook log:
<img width="349" alt="Screenshot 2023-09-06 at 20 32 31" src="https://github.com/richardtallent/vue-simple-calendar/assets/7606307/a115633c-350f-4a15-b06c-df5b17874158">
It's in "+02:00", while I'm in "-04:00".

**Comment by richardtallent** [comment]
Fixed in 7.0, thanks!
