### ISSUE TITLE
Day order

### ISSUE THREAD

**Issue by ag0n-e** [richardtallent/vue-simple-calendar#229]
Is it possible to influence the sorting of items within a day? The fact that longer periods of time appear higher up is ok, but how to sort the events per day/attribute?

**Comment by richardtallent** [comment]
The items are sorted by the `startDate` attribute, so if the time of day is included in your values for that and there are non-spanning events on the same date, they should already be sorted by their respective times (after any events that span multiple days).

In the next few minutes, I'm releasing a minor version that will fix how the events with time of day ranges weren't stretching across their entire date.

**Comment by ag0n-e** [comment]
Thank you for the explanation! All clear. And thanks also for the update!
