### ISSUE TITLE
v7.0 error [vite:resolve] Failed to resolve entry for package "vue-simple-calendar"

### ISSUE THREAD

**Issue by lianee** [richardtallent/vue-simple-calendar#230]
Hi,

full message:
`[vite:resolve] Failed to resolve entry for package "vue-simple-calendar". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vue-simple-calendar". The package may have incorrect main/module/exports specified in its package.json.`

in vue-simple-calendar/, there is a file named vue-simple-calendar.js, but in package.js, it is expected to be vue-simple-calendar.mjs (like in v6.3.1)

Renaming the file to vue-simple-calendar.mjs fixes the issue (or changing package.json)

**Comment by christophbeberweil** [comment]
Hi @richardtallent, I implemented @lianee suggestion in #231. Please contact me if any further work is necessary to resolve this issue.

**Comment by richardtallent** [comment]
Published in 7.0.1
