### ISSUE TITLE
Month skipping in month view

### ISSUE THREAD

**Issue by yogeshgalav** [richardtallent/vue-simple-calendar#234]
When using month view with Japanese local,
It skips February month for 2024 each time I switch month with header.

**Comment by richardtallent** [comment]
I switched my locale to Japanese and was not able to reproduce. Are you sure you are passing in an ISO date **string** rather than a localized date? If not, this may be a time zone issue.

**Comment by yogeshGroony** [comment]
I couldn't reproduce it now, But this issue was raised by our QA team, hence will reconnect if occurs again.
