### ISSUE TITLE
Items with padding

### ISSUE THREAD

**Issue by get-Friday** [richardtallent/vue-simple-calendar#245]
I have a question about how do I adjust the top calc with items that have a padding.

![image](https://github.com/user-attachments/assets/bf704c98-63ab-4772-a8df-bfd777329575)

Im currently having this issue with my items. Where I set a padding to them and the calc isnt enough to give them space so they overlap.

I read about issue #178 but I couldnt really understand how they changed the calc to update items position

I just want my items do have a bigger size so I can give them some more content inside.

**Comment by get-Friday** [comment]
Solved it!!

as said [here](https://github.com/richardtallent/vue-simple-calendar/issues/178#issuecomment-850000409) I just passed `:item-content-height="'3em'"` to my calendar-view and now I have more space to work with the content inside my cv-item.

**Comment by richardtallent** [comment]
This is the way
