### ISSUE TITLE
Not only single click events

### ISSUE THREAD

**Issue by Goomba41** [richardtallent/vue-simple-calendar#246]
In my project, I want to make an action by double-clicking on an item in the calendar. However, this functionality has not been implemented. Maybe it would be a good idea to implement more events than just one click (e.g., dblclick, context menu, and others)?

**Comment by richardtallent** [comment]
I don't have time to address this at the moment, I'm happy to accept a PR. Or you can implement it yourself with a custom `item` slot.

**Comment by Goomba41** [comment]
Oh, I completely forgot that I have already implemented this through a custom item slot, I think about close the issue
