### ISSUE TITLE
Couldn't fin preset "env"

### ISSUE THREAD

**Issue by AllanVieira** [richardtallent/vue-simple-calendar#26]
Hello, I am trying to use the component however after following the steps of Installation and use I came across this error.

Any idea what might be happening?

Error in ./~/vue-simple-calendar/src/components/calenda-month.vue

Module build failed: Error: Couldn't find preset "env" relative to directory "c:\\Users\\allan_vieira\front\sicred-front\\node_modules\\vue-simple-calendar"

![erro calendar png](https://user-images.githubusercontent.com/7756932/33561977-3cfd8398-d8fb-11e7-97d6-2c16436cf128.PNG)

**Comment by richardtallent** [comment]
Hi Allen,

What version of npm are you using, which version of babel, and do you have babel-preset-env installed?

For comparison, I'm using npm 5.5.1, and the calendar test app I used to create the documentation has babel 6.26.0 with babel-preset-env 1.6.1 installed.

**Comment by richardtallent** [comment]
I believe I found the culprit... the babel config was referencing an unnecessary preset. Please update to version 1.7.1 and see if that resolves the issue. Thanks!

**Comment by AllanVieira** [comment]
Hi Richard 

Nice, I updated and it worked, thank you.

**Comment by richardtallent** [comment]
Glad to hear it!
