### ISSUE TITLE
3 Events on same day displayed incorrectly within the calendar grid.

### ISSUE THREAD

**Issue by ericdiviney** [richardtallent/vue-simple-calendar#29]
Hi there! When I have 3 events all on the same day in my google calendar, for some reason they are displayed oddly in the table-cell for that date. Each event starts and ends on the same date -  but as you'll see in my screenshot, 

- 1 event displays correctly (test event 1)
- Another event displays on the _wrong_ date (test event 3)
- And the last event spans two days in the calendar vue, even though according to my calendar it only spans 1 day. (test event 2)

Attaching a screenshot to help! Thanks!
![example](https://user-images.githubusercontent.com/5143860/34181314-691d5592-e4d7-11e7-988e-31996e7b9bfa.jpg)

**Comment by ericdiviney** [comment]
Sorry. After messing around with timezones, and noting that the plugin (at this time) disregards times, I think there was something odd going on when I loaded the events into the plugin. 

Working as expected now.

**Comment by richardtallent** [comment]
No worries, that was my first guess as well. IMHO (and I think Jon Skeet would agree), the old adage about "two hard things about programming" should have another item for dealing with flippin' time zones. :)
