### ISSUE TITLE
NPM & Yarn

### ISSUE THREAD

**Issue by AshboDev** [richardtallent/vue-simple-calendar#3]
Hey Rich,

Regarding getting this on NPM I'd love to see this! Currently manually using this in a new project and just trying to get the next and previous buttons working!

I found this which might be of help: https://docs.npmjs.com/getting-started/publishing-npm-packages. Also we use Yarn a lot, and I know many others do so might be worth looking at getting it up on there too: https://yarnpkg.com/en/docs/creating-a-package

If you want to give it a shot, let me know and I'll try it locally when done :)

**Comment by richardtallent** [comment]
Thanks Ash! I believe I've successfully published it on npm:

https://www.npmjs.com/package/vue-simple-calendar

Can you give it a shot?

I also upgraded the Vue dependency to the latest (2.3.3).

**Comment by AshboDev** [comment]
Hi Rich,

Looks like it was a success :D

![image](https://cloud.githubusercontent.com/assets/14421977/26344152/87a8ad4a-3f96-11e7-8368-35ae83b03b6b.png)

Well done man!

**Comment by AshboDev** [comment]
Looks like YarnPKG has synced with npm and has successfully installed through Yarn too:

https://yarnpkg.com/en/package/vue-simple-calendar

What a way to start a Tuesday! :D

**Comment by richardtallent** [comment]
Thanks! Honestly I thought putting a Vue component on npm would require some complex incantation, specific folder structure, or entry file. Pleasantly surprised.
