### ISSUE TITLE
Yearly

### ISSUE THREAD

**Issue by TartanLeGrand** [richardtallent/vue-simple-calendar#30]
Hello,

I would like to know if there is already a function that can display the calendar by years.

Thank's for your reply.

**Comment by richardtallent** [comment]
Not yet! I’m considering a week view, basically the same as the month view but only one week of data and the arrows at the top would move between weeks. Once that is done, it should be pretty simple to extrapolate further to create a calendar that is 52-54 weeks high (though that would be one y’all calendar!).

If you’re thinking of something different than what I’m describing, do you have an example?

**Comment by richardtallent** [comment]
Closing this issue... version 2.0 has been released, it supports week, month, and year views (including multiples of any of those). Just be sure to give the component plenty of height in your layout to actually show all 52-ish weeks. If there's not at least 3em available height for each week in the view, it will scroll the view, but 3em barely fits one event per day.
