### ISSUE TITLE
Overflowing Events

### ISSUE THREAD

**Issue by arvidkahl** [richardtallent/vue-simple-calendar#35]
Hello Richard, thank you so much for this fine component!

I am trying to figure out how to deal with events overflowing their respective day. As you align them absolutely, scrolling within the day is not really an option. Do you have any suggestions? Would you think attempting to refactor the day + events into a self-sizing, scroll-compatible flexbox would be good? I can likely provide a pull request if you feel this is a good idea, but since I expect you already have some experience / learnings from building the thing in the first place, I'd ask.

**Comment by richardtallent** [comment]
Hi,

You've reave my mind! :) I'm actually an hour or so (I hope) from releasing 2.0, which supports vertical scrolling on weeks that have too many events to show, *and* the ability to scroll the entire period if the calendar component is too short to show the entire period. I'm also increasing the minimum cell height to 3em to ensure at least one event has room to show up below the date, along with a sliver of the next so the user knows there's more to be seen.

I'll add this as a mention on that commit so you'll know when it's ready to test.

**Comment by arvidkahl** [comment]
Wow, what a great late Christmas present. I'll be happy to check it out as soon as you release it :D

**Comment by richardtallent** [comment]
Closing this issue... version 2.0 is out, which supports scrolling both for individual weeks with too many events to see, and for grids that don't have enough room to show all of the weeks in the current period. You can see how this works in the demo app, there's a day there with more sample events than fit in the default monthly view.

With some overrides, it may be possible to scale the grid's week height dynamically based on the number of events, but this would lead to an aesthetically poor design, so I've been looking for solutions that retain the elegance of a grid with consistent row heights.
