### ISSUE TITLE
Those event names are causing some issues. set-show-date

### ISSUE THREAD

**Issue by phil-w** [richardtallent/vue-simple-calendar#37]
The demo shown here causes the Vue development tools to barf with the message below. The cause is that the event name is emitted as setShowDate instead of set-show-date (line 329 etc).

That works ok if you embed this as a component inside another Vue component, but if (like me) you just want to drop it into a HTML file then... it doesn't work. The work-around is to rename the events in the distribution so the event names have hyphens in them, then it works.

Oh, other events have the same issue.

--- 
""Event "setshowdate" is emitted in component <CalendarView> at src/CalendarView.vue but the 
handler is registered for "setShowDate".  Note that HTML attributes are case-insensitive and you cannot use v-on to listen to camelCase events when using in-DOM templates. You should probably use "set-show-date" instead of "setShowDate".

**Comment by richardtallent** [comment]
Hmm... I thought that would be a quick fix, but apparently if you *are* specifying `@event` attributes in another Vue component, you *can't* use kebab-case -- it doesn't work (though it works fine for props).

It's not clear from the Vue docs whether this is a purposeful limitation or a bug. I put out a feeler on the Discourse channel to see if anyone else has more information.

**Comment by phil-w** [comment]
I thought I'd fixed it by quickly hacking the event names to being hyphenated. That seemed to work. However overall I decided to nest the component in a wrapper as I wanted to take the controls out of the display anyway. That gives me what I want: a simple low-dependency calendar shell I can render my own stuff into.
