### ISSUE TITLE
outsideOfMonth doesn't work when you change months

### ISSUE THREAD

**Issue by phil-w** [richardtallent/vue-simple-calendar#38]
Well it depends what it's supposed to do. I expect it should be used to decorate days which are not in the month being shown - the max 6 days at the start and the end. If you check the demo, you can see the defect.... click "next month", and pretty much everything is out side that "next" month. Maybe that's by design, but it's not what I'd expect.

**Comment by richardtallent** [comment]
You're right! Some date math was refactored in the last version and this was comparing against today's date rather than the "current month" (i.e., the month of showDate). This has been been fixed in 2.0.1. Thanks!
