### ISSUE TITLE
Change style of interacted day/event

### ISSUE THREAD

**Issue by sazarkin** [richardtallent/vue-simple-calendar#39]
Sorry if i missing somethin, but is there a way to change style of clicked day/event?
It will be very nice to have special class added to clicked element.

Thanks for the solid component!

**Comment by richardtallent** [comment]
Thanks Sergei!

This would require the component itself to manage the state of knowing which events had or had not been clicked, and it's not clear what would then cause an event to lose that status (that could be application-dependent, such as taking the class off after a dialog showing event details is closed).

Fortunately, this should be pretty easy to do from your own page/component by listening for the `click-event` event and modifying your event's `classes` key. Something like the following (I haven't tested this code):

```HTML
<calendar-view
  @click-event="onClickEvent"
  @show-date-change="setShowDate"
  :show-date="showDate"
   :events="events"/>
```

```JavaScript
methods: {
// ...
  onClickEvent(e) {
    e.classes += " clicked"
  }
}
```

**Comment by sazarkin** [comment]
I guess you can do it stateless way.
Add prop `custom-day-classes`. And there will be mapping: `{'2018-01-01': [list of my extra clasess for this day]}`.

**Comment by richardtallent** [comment]
Ah! Yes, the events do pass in their classes, but there's not a direct mechanism for doing so with dates. Each date *is* given a class representing its date (several forms actually), but styling them dynamically would be tricky. I'll put some thought into it, but I do think a date/classes dictionary makes sense.
