### ISSUE TITLE
Demo issue

### ISSUE THREAD

**Issue by totaltrash** [richardtallent/vue-simple-calendar#4]
When I click on a date in your demo, it reports that I clicked on a different date. For instance, if i click on 22 June 2017, it reports "You clicked: 2017-06-21".

I haven't looked any deeper, but could it be a locale issue (I'm east coast Australia, GMT +10)?

**Comment by richardtallent** [comment]
Thanks! I made a change last night to make the message "prettier" by showing the date clicked in ISO format. It appears that in setting the format, I also apparently am formatting it for GMT. Will fix and check to see if I've made other obvious assumptions about time zones.

**Comment by richardtallent** [comment]
Fixed! Swapped out the ISO date formatter for one that returns the date according to the user locale settings.
