### ISSUE TITLE
IE11 Not Working

### ISSUE THREAD

**Issue by etiennellipse** [richardtallent/vue-simple-calendar#46]
Very nice project, congratulations.

I would like to use it for my client's platform, however they support the following browsers: 
- Chrome (desktop & Android)
- Firefox
- Safari (Mac & mobile)
- Edge
- Internet Explorer 11

I found no indication of which browsers are supported in the readme, and found out that the demo page does not work on IE11. I get **TypeError: Object doesn't support property or method 'fill'**, which could be fixed easily by a polyfill. But maybe it's a conscious decision on your part not to go there.

Anyway it would be nice to have the supported/tested browsers in the readme.

Also, the readme contains a **lot** of information. You could split that into release notes (for breaking changes and such) attached to the release and move some into the Wiki pages. It would make it easier for people to discover your projet and evaluate it, I believe.

Keep up the great work!

**Comment by richardtallent** [comment]
Thanks!

IE11 should be supported, and has been tested in the past. I think something went wrong when Babel changed how we configure polyfills ("env" was supposed to fix everything... guess not). I've modified my local .babelrc file, but can't test it at the moment as I'm stuck mid-upgrade to Webpack 4. You may be able to get it working by replacing your local copy of .babelrc with this:

```
{
	"presets": [
		[
			"@babel/preset-env",
			{
				"useBuiltIns": "entry"
			}
		]
	]
}
```

Same with browser compatibility--there used to be a section for it, it probably got whacked in a previous PR where someone re-organized the readme. I usually test on IE11, Firefox (Mac), Safari (Mac), Chrome (both), Safari (iOS), Edge, and the Silk browser on my cheap Amazon Fire tablet.

I agree about the readme length and complexity. I'm working on v3.0 now, and when it comes out, the readme will include only information about 3.0, I'll move any mention of 1.x and 2.x migration to another page.

I've rolled this babelrc update into version 2.2, which I'm working on now and should be able to test and publish as soon as the various libraries used by the standard Vue template catch up with webpack 4. I'll leave this open as a reminder to self to re-test in IE11 before publishing it.

**Comment by richardtallent** [comment]
Still working on webpack 4 support. Got it almost working. But the above preset I found is apparently from a babel 7 beta, not the release version, so I don't have anything to test IE11 with yet.

**Comment by richardtallent** [comment]
I released 2.2.0, but despite much Googling and testing, I was not able to restore IE11 support. It seems to simply come down to Babel not transpiling. I'll leave this issue open for now, in hopes that someone with more experience with webpack and babel can figure out the problem.

**Comment by etiennellipse** [comment]
Here is the .babelrc that we use for our project:
```
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 3 versions", "ie >= 11"]
      }
    }]
  ]
}
```
Which reads as: support last 3 versions of every browser AND IE11+. This way, your compiled bundles will always support IE11.

**Comment by richardtallent** [comment]
Thanks! I'll give that a shot, might have some time tonight to try.

**Comment by richardtallent** [comment]
With some adjustments to the browserlist config, polyfill loading, and a CSS fix, it looks like IE11 is now supported again! 2.2.1 is live here on the master branch of the repo.

I can't log in to npm for some reason from my work laptop and I'm on a business trip, so I won't be able to publish it for a few days, but you can clone and work from the source if needed in the meantime.
