### ISSUE TITLE
Allow X-days period

### ISSUE THREAD

**Issue by trollepierre** [richardtallent/vue-simple-calendar#48]
I would like to display a calendar with 8 days

**Comment by richardtallent** [comment]
This component is designed specifically for the standard Gregorian calendar, and there are too many design assumptions around standard calendars to parameterize the number of days. I wouldn't even have a clue what a real-world use case for such a calendar would be, how days would be labeled, what the origin calculation would look like, etc. I've considered a "work week" calendar (5 or 6 days), but that sort of change would really just be a 7 day calendar with some days hidden, it wouldn't really impact the overall concept of a days and weeks.

I'm afraid this really isn't the right tool for whatever you're trying to achieve. Best of luck finding something that better fits your use case!
