### ISSUE TITLE
Version 1.5 Goals

### ISSUE THREAD

**Issue by richardtallent** [richardtallent/vue-simple-calendar#5]
I have a few small goals for v.1.5, feedback welcome:

1. *Minimize* component-level CSS. Like HTML itself, the best web components are styled primarily by the calling page. Any CSS not needed for the functionality of the calendar itself will be moved to an external spreadsheet so users can more easily theme their own calendar.

2. Enable drag and drop on mobile. Possibly enable "ghost" positioning during the drag event (i.e., being able to see the other events "open up" the place where the current event would be positioned).

3. *Considering* using some style attributes rather than classes for positioning of events. Using classes makes it more complicated than it should be for someone to tweak the style of the events (padding, borders, font size relative to the calendar, etc.). Not decided yet. CSS variables would be better, but the web just isn't there yet.

4. Fix a few issues I believe could still crop up related to use of date.toIsoString() when I really just want the *local* date in ISO format.

5. Clean up and organize the methods. My gut tells me I'm over-using methods and there's a cleaner way to handle all of the miscellaneous date transformation/comparison methods. In general I feel like some of the state management of the dates and events should be less coupled to the specific header and template I'm using, since much of it could be used for date-picking or other calendar-related components.

**Comment by richardtallent** [comment]
I took on #1, 4, and 5 for v.1.5. I believe #3 is basically handled now that I've done #1 and reorganized the CSS to be more consistent in metrics.

Didn't get to #2, so I'll leave it open for 1.6. Haven't done touch-based drag and drop before, and it's certainly a bit more complicated than on the desktop. For that, it may be best to add a dependency to a helper library.

**Comment by grafa** [comment]
Hey man I just want to say this is amazing component. Javascript world is really missing calendar in Gogole Calendar style or similar. All these datepickers are just same with no ability to show events or so.

I just wanna say keep up!

**Comment by richardtallent** [comment]
Thanks @grafa! This component was one part "scratching my own itch" and one part a learning exercise for creating a reasonably complicated Vue component. I'm happy that it's useful to other people!

**Comment by grafa** [comment]
I've forked your repo and implemented some stuff. I tried to keep each commits as tiny as possible so maybe you can `cherry -pick` some of them. Feel free to do so.

**Comment by houseoftech** [comment]
grafa's changes look good.

**Comment by richardtallent** [comment]
Moved 2nd item to new issue #21. Closing the remainder.
