### ISSUE TITLE
Proposal for new class names

### ISSUE THREAD

**Issue by richardtallent** [richardtallent/vue-simple-calendar#52]
In 3.0, I'd like to revamp the current primary class names to be flatter (more unique, with no cascaded selectors needed to target most elements), which will simplify both the core and default CSS as well as custom themes. Here are my thoughts so far:

Element | Current Class | New Class
------------ | ------------ | -------------
Root | calendar-view | cv-wrapper
Header | header | cv-header
Period | periodLabel | cv-header-period
Button area | nav | cv-header-nav
DOW header | dayList | cv-header-days
DOW name | day | cv-header-day
Weeks | weeks | cv-weeks
Week | week | cv-week
Day | day | cv-day
Day content | content | cv-day-content (may look into removing this, can't recall if it's needed anymore)
Day number | date | cv-day-number
Event | event | cv-event

Note that while the list  of day names is a "header" of sorts, it lives below the `div.header` element, not as a child of it (no change there).

No changes are proposed currently for the "modifier" classes (such as `dMM-DD`, `instanceX`, and `singleMonth`).

However, I am considering dropping the complex `periodLabel` child elements and just using a function (and like everything in the header, adding a slot to override it) to format the date period. The CSS-only thing was a cool use of pseudo-element content, but isn't easy to override and makes localized assumptions about date formatting. CSS content for the header buttons will also be replaced with static text, with slots to allow replacing the buttons.

I also need to test to see if I can remove the z-index calculation for weeks and events. Recent changes to how weeks are rendered may make these computations unnecessary.

Finally, I'll be looking into replacing the `eventRowX classes with a calculated `style`. This will remove the artificial limitation of 20 events in a given day (as high a number as that is), and should make it easier to override if your slotted or themed events' padding/border/font metrics don't match the default.

**Comment by dolbex** [comment]
All seems very logical. Looking forward to the simplifications

**Comment by richardtallent** [comment]
Implemented in 3.0, which is about to launch
