### ISSUE TITLE
Why is `require(../../etc/file.css)` found in a script tag?  Causes parse errors for me.

### ISSUE THREAD

**Issue by samfullman** [richardtallent/vue-simple-calendar#54]
in the README.md file there is this code:

```HTML
<script>
	import CalendarView from "vue-simple-calendar"
	require("vue-simple-calendar/dist/static/css/default.css")
	require("vue-simple-calendar/dist/static/css/holidays-us.css")
</script>
```
However, including the two `require()` directives results in a parse error for me; the compiler is treating the CSS, well, as CSS.

Am I missing a plugin or is my environment not right?  Please and thanks for your help.

**Comment by richardtallent** [comment]
The “require” statements would be if you’re using webpack, as this converts those CSS files into bundled resources that can (optionally) be downloaded only as needed. 

To use the calendar without webpack, you would just use link tags as you would with any other CSS.
