### ISSUE TITLE
Modify calendar day cell's class based on event's click

### ISSUE THREAD

**Issue by LTroya** [richardtallent/vue-simple-calendar#55]
Hi,

Is there a way to change the calendar day cell's class based on an event click? A simple use case will mark the cell as selected if an event of that specific day is clicked. 

At this moment, I am making the event take all available space on the calendar day cell and change its class. But the issue is I lose the current day. I think to add it manually

Something like this: 

![screen shot 2018-04-04 at 18 46 37](https://user-images.githubusercontent.com/6491259/38336697-13f02b16-3839-11e8-869c-20914b2e8e4e.png)

I will appreciate any hint. Thanks in advance.

**Comment by richardtallent** [comment]
Thank you! I've merged it into the new 3.0 branch, which I'm working on this morning.
