### ISSUE TITLE
Height doesn't adjust

### ISSUE THREAD

**Issue by MaxMueller94** [richardtallent/vue-simple-calendar#58]
I took the minimal application example for a calendar and added some events.
However it seems like the height of the cells doesn't adjust to the number of events so it only shows one event for each day.

**Comment by richardtallent** [comment]
Hi Max,

This control is designed to use Flexbox to create a grid where each week has a *uniform height*, like a standard calendar. The events float on top of this grid.

The calendar takes the height of its parent element. If the parent has no defined height (either using normal CSS min-height/max-height, or using flexbox), the calendar will default to a minimal size--just enough to show the day number and about 1 event row per week. I believe that's the behavior you're seeing.

You can also set the calendar control's height using CSS, like the sample application does for year-view and multi-month views, and if this height exceeds the parent height, the calendar grid (but not the header) will scroll inside the parent.

https://github.com/richardtallent/vue-simple-calendar-sample/blob/master/src/App.vue

If your chosen grid height still isn't tall enough to show all events for a given week, the user can scroll the week up and down to show the other events.
