### ISSUE TITLE
Seems like URL is not working!

### ISSUE THREAD

**Issue by debnath4u** [richardtallent/vue-simple-calendar#60]
startDate: reservationData.time_raw,
            endDate: reservationData.time_raw,
            title: '<p>' + reservationData.name  + '</p>',
            id: 'id' + reservationData.id,
            url: 'http://google.com',
            classes: ''

All working good, but not url, any suggestion?

**Comment by richardtallent** [comment]
Hi Deb,

Good catch! The documentation is outdated. While there is still an optional `url` key for events, the only action taken by the calendar component in response to a URL value is to add the "hasUrl" class to the event, so events with links can be styled by the calling application appropriately (for example, the "default" theme underlines these on hover).

The calling application is responsible for "following" the link, by listening for the `click-event` event and responding as appropriate. Depending on the application, this "following" may involve a simple `window.location` change, opening a pop-up window, showing an in-page dialog or tab, having Vue Router push or replace an SPA route, etc. The sample application shows how to listen for clicks on an event.

Hope that helps! I'll leave this open to remind myself to update the docs.

**Comment by debnath4u** [comment]
Thanks for your quick reply!

I solved the issue by using HTML tag in title element.

Now I have one more issue, is it possible to make scroller to work for each day? Right now what I am seeing if I use scroll up/down its scrolling whore row instead of just that day.

Please let me know if its possible.

**Comment by richardtallent** [comment]
It's not possible to make the scroller different for each day. One of the key features of this component is support for events spreading across multiple days, so for the purposes of the events layout, the week is the parent, not the day.

**Comment by richardtallent** [comment]
Documentation regarding the `url` attribute has been updated for 3.0, which is about to launch... thanks!
