### ISSUE TITLE
Agenda

### ISSUE THREAD

**Issue by rjimenezg** [richardtallent/vue-simple-calendar#63]
Any plans for an agenda in the future? I read in the Features section: "There is no "agenda" view (time-of-day grid). This would require adding too much complexity."

But is there a plan for this? Also, if there is a hint on how to do it, I could help with it.

**Comment by richardtallent** [comment]
There are no plans.

I thought about what it would take (see #47), and it would require adding far too much complexity to the component's logic and layout -- complexity that would not benefit the primary use case of a simple, high-performance *month*-view calendar.

I do think someone could borrow portions of the code here and create an agenda-specific component (or any other sort of calendar), I just wouldn't be the person to do it.
