### ISSUE TITLE
Question: "slotX" classes?

### ISSUE THREAD

**Issue by Dylan-Chapman** [richardtallent/vue-simple-calendar#66]
I've tweaked some calendar styling (the days of the month are slightly larger) and I need to adjust the event's "top" positioning. The README says "you'll have to change the slotX classes as well to position the events vertically in the right place".  However, I can't find any "slotX" classes mentioned anywhere or in the code. Is there some way to adjust the top positioning without having to override the entire event slot?

**Comment by richardtallent** [comment]
Hi Dylan,

You're right! I removed `slotX` and intended to add another mechanism for tweaking the event positioning, but it didn't make it into 3.0.0. I've added some additional properties in 3.0.1 to handle both changes to the `cv-day-number` and `cv-event` effective heights.

**Comment by Dylan-Chapman** [comment]
Works perfect - thanks! Side note, the README says the prop is called ```eventsTop``` when it's actually ```eventTop``` (singular)
