### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by slava-the-human** [richardtallent/vue-simple-calendar#7]
Hello! Can you add some basic information like "Getting starting" or simple example?

**Comment by richardtallent** [comment]
Excellent idea! I saw a presentation showing how Storybook (https://github.com/storybooks/storybook) now supports Vue, so I'm considering using it as a way to show some simple examples (and to build a set of useful visual tests).

In the meantime, the "Demo" app included in the repository shows a simple Vue application that uses the calendar, feeds it some sample data, and implements the optional hooks needed for drag and drop and clicking dates and events:

https://github.com/richardtallent/vue-simple-calendar/blob/master/src/App.vue

**Comment by Raklaite** [comment]
Thanks for the amazing vue-simple-calendar components released four days ago , spend many hours to find and integer a good one without Jquery and easy to fill event with Google calendar API. Really thanks Richardtallent

**Comment by MarsZone** [comment]
First thanks a lot for this project.Very useful to me.
and,
https://github.com/richardtallent/vue-simple-calendar/blob/master/src/App.vue
This 404 page not found.

**Comment by richardtallent** [comment]
Thanks @Raklaite and @MarsZone! I'm closing this issue now, I think the docs now are in better shape for newcomers, and with the sample app extracted to its own repo, it's pretty simple to get an app going to play around with the calendar.
