### ISSUE TITLE
How do I customize header?

### ISSUE THREAD

**Issue by kiennguyen1101** [richardtallent/vue-simple-calendar#74]
Hi, 
I'm new to Vue; I've read about using slot and could use it in simple cases. However, in Simple Calendar, I cannot customize header without re-implementing most of it's functionalities like next period, previous period, label (changing structures, adding icons... but buttons won't work). I can't simply pass this.$refs.calendar.headerProps to header slot either.
How do I make use of all the functions of Simple Calendar when using header slot?

**Comment by richardtallent** [comment]
Hi,

The wording of the Vue documentation around scoped slots could be improved. The good news is it means you don't have to re-implement anything! The `calendar-view` component passes `headerProps` as an attribute to the header slot (see line 15 of `CalendarView.vue`), and that `headerProps` object contains everything you need for your own custom header. All you have to do is get access to that attribute and pass it to your component.

For example, let's say this is your custom header, and all it does it display the JavaScript of an object property called `info`:

```HTML
<template>
	<div>{{ info }}</div>
</template>
<script>
export default {
  props: {
    info: { type: Object, required: true },
  },
}
</script>
```

Let's say you register the above as `my-custom-header`, and you want to pass the `headerProps` to this `info` prop. All you would need to do is this:

```HTML
<calendar-view [...set the attributes for the calendar view here...]>
  <my-custom-header
    slot="header"
    slot-scope="t"
    :info="t.headerProps" />
</calendar-view>
```

The `slot-scope` attribute above creates a sort of "local variable" inside your `<calendar-view></calendar-view>` node that contains *all* attributes that `calendar-view` passed to the header slot.

The `:info="t.headerProps"` part then passes the `headerProps` attribute to `my-custom-header` as the `info` prop.

The `t` above can be any name you like, as long as it doesn't conflict with your parent page's props, computed props, etc.

**Comment by kiennguyen1101** [comment]
Hi,
Thank you for your answer.
I've tried but got the error: `Invalid prop: type check failed for prop "info". Expected Object, got Undefined. `
It seems like the Header component was created before the CalendarView component (I tried to import Header and listed it in components after CalendarView). Is it a bug of Vue?

**Comment by richardtallent** [comment]
That may indicate you're running an older version of Vue. Here's a live example using the latest (2.5.16):

https://codesandbox.io/s/jp6vxyvzy5

**Comment by juanjoFactoria** [comment]
hi, I tried to customize header as explained here.  My goal is use all buttons but i want to personalize the buttons. So I copy CalendarViewHader and created new component.  It's displaying well but buttons not respond. I used the same code as default, but the this.$emit("input", d) inside onInput doesn't work.  Someone can help me? Thanks a lot.

**Comment by lochstar** [comment]
I have the buttons working by taking advantage of the header slot.

```
<div
  slot="header"
  slot-scope="{ headerProps }"
  class="cv-header"
>
  <div class="cv-header-nav">
    <el-button icon="fas fa-angle-left" class="previousPeriod" @click="setShowDate(headerProps.previousPeriod)"/>
    <el-button icon="fas fa-angle-right" class="nextPeriod" @click="setShowDate(headerProps.nextPeriod)"/>
    <el-button class="currentPeriod" @click="setShowDate(headerProps.currentPeriod)">Today</el-button>
  </div>
</div>
```

```
methods: {
  setShowDate(d) {
    this.showDate = d
  },
}

**Comment by juanjoFactoria** [comment]
Thank you @lochstar . I was using as component so $emit didn't work. Now works perfectly

**Comment by tristanvdl** [comment]
Is there a way to retrieve the label into the custom header? I can't seem figure it out
