### ISSUE TITLE
Class for current/clicked date

### ISSUE THREAD

**Issue by soxepo** [richardtallent/vue-simple-calendar#78]
Hey man!
Awesome component. 
Can you help me? How can I add class to the clicked date field or to current date?

**Comment by richardtallent** [comment]
Thanks!

The current date already has a class -- "today". You can override the style for that class any way you like. Note that "today" is based on the user's locale.

The `show-date` only drives which date period is shown in the calendar, it has no special classes or meaning outside of that. For example, for a monthly calendar, any showDate within that month results in the same rendered HTML.

The component doesn't keep track of clicks on dates, it merely pushes them back to the parent component/page (using the `click-date` event). So it has no state that is specific to "clicked" vs. "unclicked" dates.

However, there is a `prop` called `dateClasses` that allows you to pass key/value pairs, where the key is a date (in ISO form, i.e., as a "yyyy-mm-dd" string) and the value is an *array* of strings with additional classes to apply to that particular date. This would allow you to not only create semantics around a "selected" date, it would also let you model more complex activities, like selecting multiple dates or selecting date ranges.

Here's some example, **untested** code for tracking a single "selected" date:

```HTML
<template>
  <calendar-view
      :show-date="showDate"
      :date-classes="selectedDate"
      @click-date="onClickDate"
      @show-date-change="onShowDateChange"
  />
</template>
<script>
  export default {
    data: () => {
      showDate: new Date(),
      selectedDate: {}
    },
    methods: {
      onClickDate(d) {
        this.selectedDate = { [d.toISOString().substring(0,10)]: ["ClassForSelectedDate"] }
      }
      onShowDateChange(d) {
        this.showDate = d
      }
    }
  }
</script>
<style>
  .ClassForSelectedDate {
    background-color: #ffe;
  }
</style>
```

My coffee has not fully activated this morning, so I'm not quite sure if `toISOString()` here could have some edge cases of rendering the wrong date string depending on the user's time zone. Something to keep an eye on. If it happens, there's a function in `CalendarMathMixin` that renders an ISO-like date while ignoring the browser's time zone.

Hope that helps!

**Comment by MrSnoozles** [comment]
Hey Richard,

I'm struggling with something similar at the moment. I have several calendars for different users. When a date is clicked I want to add an event for the user the calendar belongs to.

In code I would like to do something like this:

~~~
<div v-for="user in users">
 <calendar-view @click-date="onClickDate(user, date)" />
</div>
~~~

Is there a way that would be possible?

**Comment by MrSnoozles** [comment]
Aaand answering my own question already. The code works with a small modification:

~~~
<div v-for="user in users">
 <calendar-view @click-date="onClickDate(user, $event)" />
</div>
~~~


**user** then contains the user variable from the loop
**$event** contains the date

Richard, VueSimpleCalendar is by far the most amazing and thought out calendar I have ever worked with, thank you so much for providing it.
