### ISSUE TITLE
previous/next period does not adjust for period count

### ISSUE THREAD

**Issue by lochstar** [richardtallent/vue-simple-calendar#79]
I've noticed `previousPeriod` and `nextPeriod` adjust the first month of a period, instead of skipping forward in groups of 2 or 3 as set by `displayPeriodCount`. Is this intentional behaviour? I would expect it to go forward or back by the set period. Google Calendar for instance when set to "2 weeks", will skip forward or back by two weeks.

**Comment by richardtallent** [comment]
I've improved the docs and added new `headerProps` for 3.1 (currently under development) to provide developers with this option, so closing this issue. Thanks!

**Comment by lochstar** [comment]
Cool, thanks for the clarification.
