### ISSUE TITLE
Display Week - FirstDayOfWeek - Event of the next week come on the current week

### ISSUE THREAD

**Issue by Oipnet** [richardtallent/vue-simple-calendar#82]
Hello

When I display the week calendar with first day Sunday with event when there is an other event the next Sunday it's display over.
When I navigate over the week and come back it's OK
For other days it's OK
I think there is a problem of max date.

Thanks a lot

**Comment by richardtallent** [comment]
Hi,

Can you provide an example on a code-sharing site? Given this description, I was not able to reproduce the issue.

Thanks

**Comment by richardtallent** [comment]
Closing due to non-activity, please feel free to re-open if you can provide a live example exhibiting the issue.
