### ISSUE TITLE
Use data-field outside calendar-view

### ISSUE THREAD

**Issue by adarshsosale** [richardtallent/vue-simple-calendar#87]
I need to separate the calendar view and the data for my vue project. I'm looking for something along the lines of [this](https://imgur.com/a/b5Ugb7k). The sidebar here is used as a different component. Any way to achieve this separation, or do I have to write a custom component for this?

**Comment by richardtallent** [comment]
This wouldn't be the component you're looking for, unfortunately. But there are a number of date picker and similar components that look more like what you're looking for, you'd just need to wire them up to a component to show the events for the selected date.

Check this out for possible calendar components:

https://github.com/vuejs/awesome-vue#calendar

**Comment by adarshsosale** [comment]
Thank you so much! Loved this component otherwise! Any plans to bring in this kind of a modularity in the future?

**Comment by richardtallent** [comment]
Thanks! 

That sort of side-by-side view would require completely different markup and logic, so it's not in the cards for this component. However, much of the date logic used by this component is in the `calendar-math` mixin, so if someone were to try to create such a view, they wouldn't need to start from scratch.
