### ISSUE TITLE
Make mixins file and vue file in the same base directory...

### ISSUE THREAD

**Issue by sean-atomized** [richardtallent/vue-simple-calendar#9]
I think the mixins file and the vue should be in the same base directory, for instance:

`/components/calender-month.vue`
`/components/mixins/mixin-calendarMath.js`

Then change the `imports` to match.  Not a hard change when including the code in your own projects, but allows for self containing if a 3rd party is using a common components directory for multiple 3rd party components (like we are) 😄

**Comment by richardtallent** [comment]
Good point. Will push that into the fix addressing the week count issue.
