### ISSUE TITLE
Vue warning when using slot dayContent

### ISSUE THREAD

**Issue by jasir** [richardtallent/vue-simple-calendar#90]
First, thank you for wonderful component.

When I use slot dayContent, I am getting this error: vue.esm.js?efeb:591 [Vue warn]: Duplicate presence of slot "dayContent" found in the same render tree - this will likely cause render errors.

Is there any info/help I should provide to you?

Thank you!

**Comment by jasir** [comment]
Seems to be related https://github.com/vuejs/vue/issues/8496

**Comment by jasir** [comment]
Well, the same for slot event, problem is that slot is rendered multiple times. It is not allowed by, vue now :(

**Comment by jasir** [comment]
Ok! It seems that if I use slot-scope, everything works perfectly. Maybe I would suggest to notice this in documentation. Closing this issue.

**Comment by richardtallent** [comment]
I'm not completely understanding the problem, since I can't see your "before" and "after" code. Would you have time to submit a rough PR on the documentation to give an example? Once I have a better grasp, I'd be happy to edit and update the documentation.

**Comment by jasir** [comment]
Basically, I have used slot without slot-scope attribute. I do not think it should go to documentation.

```
<div slot="events">
</div>
```

throws warning, while

```
<div slot="events" slot-scope="...">
</div>

does not.
