### ISSUE TITLE
this will cause 00:00 won't show on event title if showEventTimes=true;

### ISSUE THREAD

**Issue by jiujiuwen** [richardtallent/vue-simple-calendar#91]
https://github.com/richardtallent/vue-simple-calendar/blob/ca79128ebceace0ab4c65917b7164a585c3e043a/src/components/CalendarMathMixin.js#L102

**Comment by richardtallent** [comment]
Yes, that is correct. This is covered in the documentation:

> showEventTimes - If true, shows the start and/or end time of an event beside the event title. Midnight is not shown, a midnight time is assumed to indicate an all-day or indeterminate time. (If you want to show midnight, use 00:00:01 and don't choose to show seconds.) The default is false.

This is a consequence of the need to be able to show a mixture of some events with time of day, and other events that represent the whole day. If this creates a serious issue for your use, you could add the midnight time manually (perhaps through a map function) to your event titles. The titles are rendered using `v-html`, so you can even match the `<span>` markup that would have been applied automatically.
