### ISSUE TITLE
Incorrect CSS classes on header cells when startingDayOfWeek != sunday

### ISSUE THREAD

**Issue by ropez** [richardtallent/vue-simple-calendar#93]
Illustrated by this image with `startingDayOfWeek=1` and `.dow6, ,dow0 { background-color: red}`:

![image](https://user-images.githubusercontent.com/431220/44942604-c922ff80-adb5-11e8-820d-0e935a6f5b06.png)

Expected CSS classes `.dow[0-6]` on header cells to line up with day cells.

**Comment by richardtallent** [comment]
Good catch! Confirmed as a bug.

**Comment by richardtallent** [comment]
This has been fixed in 4.1.0. Thanks!
