### ISSUE TITLE
[Feature Request] Allow events to be dropped on other events

### ISSUE THREAD

**Issue by ShinyTimes** [richardtallent/vue-simple-calendar#96]
Hi,

We have need of the possiblity to drop events on other events, and then have them scheduled to the corresponding date. This should be easily achieveable by returning the startDate field of the event, instead of the day itself. Problem is, if we add this into the code ourselves, we'll have to update this each time there's an update to the calendar tool itself. Is there a possiblity of this being added in in the near future?

Regards,
ShinyTimes

**Comment by richardtallent** [comment]
Hi,

This appears to be a very specialized use case -- I can think of no other calendar applications where one would drag an event on top of another event and subsequently change the dragged event's start date to match the *drop-over event's* start date. In fact, quite the opposite -- I've been planning to try to make the drop events bubble up to the date underneath, to prevent the current issue of the events getting "in the way" of dropping an event on the desired date.

I'm fairly certain you could do this using the event slot and handling the drag-related logic in that slot. If you do that, you won't need to make any changes to the control's code.

I've never attempted this, so if you run into any brick walls trying to set up drag and drop on event slots, please let me know.
