### ISSUE TITLE
Fix the height according to the events

### ISSUE THREAD

**Issue by developernaren** [richardtallent/vue-simple-calendar#97]
There is a scroll seen in the week row when there are multiple events. Is there a way that we can fit all the events in the row and adjust the height accordingly, so that there is no scrollbar?

**Comment by richardtallent** [comment]
This is not supported, for a few reasons.

The first is aesthetics--one of the design goals was to create a traditional grid veiw, not one where some weeks are taller than others.

The second, and more important one, is that the calendar markup depends on events floating on *top* of the "week" components, and are thus outside their flow. So, the event elements can't change the week container element heights directly. Something could be hacked to compute the week height dynamically based on stacked event counts, but that would be terribly messy and not a display mode I would want to build or support.

I think the best solutions would be to either make *all* weeks tall enough to handle the number of expected events, or consider giving the user a "1 week" view they can flip to for busier weeks.
