### ISSUE TITLE
How to change color of individual calendar event

### ISSUE THREAD

**Issue by jusvu** [richardtallent/vue-simple-calendar#99]
Hi! I'm newbie on vue development and just found this awesome calendar. I've been trying to change color of the event, but cannot figure out how to do it. I have tried everything without success.

For example this definition shows calendar event in it's default color and ignores the style definition:
```
<calendar-view :events="[ { id: 'e1', startDate: new Date(2018,8,30,0,0,0,0), title: 'My event', style: 'background-color: #5ffafa;' } ]" :time-format-options="{hour: 'numeric', minute:'2-digit'}" :enable-drag-drop="true" :disable-past="disablePast" :disable-future="disableFuture" :show-date="showDate" :show-event-times="showEventTimes" :display-period-uom="viewSelection"
                        :display-period-count="displayPeriodCount" :starting-day-of-week="weekStartSelection" :class="themeClasses" @drop-on-date="onDrop" @click-date="onClickDay" @click-event="onClickEvent" @show-date-change="setShowDate" />
```

I tried to remove class definition (if it somehow overrides the style definition?), but it does not change anything.

I might have wrong syntax, since I'm not familiar with vue, please help me with this =)

**Comment by jusvu** [comment]
Thank you for your answer, naulacambra! I'm using version 4.0.2
Here's what Chrome inspect shows:
Element:
`<div draggable="true" title="My event" class="cv-event offset6 span1" style="top: calc(1.4em + 0px);"> My event</div>`
...and Styles:
```
.theme-default .cv-event {
    background-color: #dff2f3;
    text-overflow: ellipsis;
}
```
If I change background-color in Styles view manually, the event color changes in the web page. 

I'm quite sure I have wrong syntax in the style definition... Should I add ".theme-default" or ".cv-event" or even both somehow? Sorry, but web SW design is something very new to me.

**Comment by naulacambra** [comment]
What "themeClasses" is?

I've tested out, and it seems to work fine (using your code)

In the `div`'s style attribute, should appear the `background-color` attribute (next to `top: ....`). Can you copy-paste your `package.json` and your code?

**Comment by jusvu** [comment]
Hi! I found the problem; I screwed up the vue-simple-calendar update. I thought it was 4.0.2, but it was not updated and it actually was 3.0.2. Thank you for your help on this problem!
